import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const consoleDirectory = resolve(scriptDirectory, "..");
const input = process.env.OPENAPI_INPUT
  ? resolve(process.cwd(), process.env.OPENAPI_INPUT)
  : resolve(consoleDirectory, "../openapi/openapi.yaml");
const outputDirectory = resolve(consoleDirectory, "src/api/generated");
const output = resolve(outputDirectory, "schema.ts");
const inputLabel = relative(consoleDirectory, input).split(sep).join("/");
const codegenDirectory = resolve(consoleDirectory, "tools/openapi-codegen");
const codegenScript = resolve(codegenDirectory, "generate.mjs");
const codegenPackage = resolve(
  codegenDirectory,
  "node_modules/openapi-typescript/package.json",
);

const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";

const run = (command, args, options) =>
  new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, { stdio: "inherit", ...options });
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (code === 0) {
        resolvePromise();
        return;
      }

      reject(
        new Error(
          `${command} exited with ${signal ? `signal ${signal}` : `code ${code}`}`,
        ),
      );
    });
  });

await mkdir(outputDirectory, { recursive: true });
try {
  await access(codegenPackage);
} catch {
  await run(npmCommand, ["ci", "--ignore-scripts"], {
    cwd: codegenDirectory,
  });
}

await run(process.execPath, [codegenScript, input, output]);

const header = `/**\n * Generated from ${inputLabel}.\n * Do not edit this file directly. Run npm run api:generate.\n */\n\n`;
const source = await readFile(output, "utf8");
await writeFile(output, `${header}${source}`, "utf8");

const index = `/** Generated API surface. Do not edit manually. */\nexport type { components, operations, paths, webhooks } from "./schema";\n`;
await writeFile(resolve(outputDirectory, "index.ts"), index, "utf8");

console.log(`Generated ${output}`);
