import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const consoleDirectory = resolve(scriptDirectory, "..");
const input = process.env.OPENAPI_INPUT ?? resolve(consoleDirectory, "../openapi/openapi.yaml");
const outputDirectory = resolve(consoleDirectory, "src/api/generated");
const output = resolve(outputDirectory, "schema.ts");

await mkdir(outputDirectory, { recursive: true });
const document = await readFile(input, "utf8");
const ast = await openapiTS(document, { enum: true });
const source = astToString(ast);
const header = `/**\n * Generated from ${input}.\n * Do not edit this file directly. Run npm run api:generate.\n */\n\n`;
await writeFile(output, `${header}${source}`, "utf8");

const index = `/** Generated API surface. Do not edit manually. */\nexport type { components, operations, paths, webhooks } from "./schema";\n`;
await writeFile(resolve(outputDirectory, "index.ts"), index, "utf8");

console.log(`Generated ${output}`);
