package cli

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type InstallPlan struct {
	Layout    InstallLayout
	Version   string
	PublicURL string
	DockerGID uint32
	Existing  bool
}

type localPorts struct {
	API     string
	Console string
	Proxy   string
}

func newInstallPlan(layout InstallLayout, version, publicURL string, dockerGID uint32) InstallPlan {
	return InstallPlan{
		Layout:    layout,
		Version:   version,
		PublicURL: publicURL,
		DockerGID: dockerGID,
	}
}

func validatePublicURL(raw string) (string, error) {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || parsed.Scheme != "http" && parsed.Scheme != "https" || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return "", fmt.Errorf("URL must be an absolute HTTP(S) URL without credentials, query, or fragment")
	}
	if strings.ContainsAny(raw, "\r\n\x00") {
		return "", fmt.Errorf("URL contains invalid control characters")
	}
	return strings.TrimRight(parsed.String(), "/"), nil
}

func generateSecretBytes(size int) ([]byte, error) {
	if size < 1 {
		return nil, fmt.Errorf("secret size must be positive")
	}
	secret := make([]byte, size)
	if _, err := rand.Read(secret); err != nil {
		return nil, fmt.Errorf("generate secret: %w", err)
	}
	return secret, nil
}

func generateHexSecret(size int) (string, error) {
	secret, err := generateSecretBytes(size)
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(secret), nil
}

func generateBase64Secret(size int) (string, error) {
	secret, err := generateSecretBytes(size)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(secret), nil
}

func generateConfig(plan InstallPlan) (string, error) {
	publicURL, err := validatePublicURL(plan.PublicURL)
	if err != nil {
		return "", err
	}
	if plan.Version == "" {
		return "", fmt.Errorf("release version is required")
	}
	if err := validateReleaseVersion(plan.Version); err != nil {
		return "", err
	}
	postgresPassword, err := generateHexSecret(24)
	if err != nil {
		return "", err
	}
	redisPassword, err := generateHexSecret(24)
	if err != nil {
		return "", err
	}
	functionsKey, err := generateBase64Secret(32)
	if err != nil {
		return "", err
	}
	metricsToken, err := generateHexSecret(32)
	if err != nil {
		return "", err
	}
	cookieSecure := "false"
	if strings.EqualFold(mustParseURLScheme(publicURL), "https") {
		cookieSecure = "true"
	}

	values := map[string]string{
		"COMPOSE_PROJECT_NAME":            "stealth",
		"STEALTH_API_IMAGE":               imageName("stealth-api", plan.Version),
		"STEALTH_WORKER_IMAGE":            imageName("stealth-worker", plan.Version),
		"STEALTH_MIGRATE_IMAGE":           imageName("stealth-migrate", plan.Version),
		"STEALTH_CONSOLE_IMAGE":           imageName("stealth-console", plan.Version),
		"POSTGRES_DB":                     "stealth",
		"POSTGRES_USER":                   "stealth",
		"POSTGRES_PASSWORD":               postgresPassword,
		"REDIS_PASSWORD":                  redisPassword,
		"FUNCTIONS_SECRET_KEY":            functionsKey,
		"PUBLIC_APP_URL":                  publicURL,
		"COOKIE_SECURE":                   cookieSecure,
		"TRUSTED_PROXY_CIDRS":             "172.30.0.0/24",
		"STEALTH_NETWORK_SUBNET":          "172.30.0.0/24",
		"DOCKER_GID":                      strconv.FormatUint(uint64(plan.DockerGID), 10),
		"METRICS_TOKEN":                   metricsToken,
		"FUNCTIONS_RUNNER_ENABLED":        "true",
		"FUNCTIONS_WORKER_ID":             "stealth-worker",
		"FUNCTIONS_RUNNER_STAGING_VOLUME": "stealth_function_runner_staging",
		"STORAGE_DRIVER":                  "local",
		"STORAGE_MAX_FILE_SIZE":           "50MiB",
		"STORAGE_DEFAULT_QUOTA_BYTES":     "1GiB",
		"PROJECT_OPERATION_RATE_LIMIT":    "120",
		"PROJECT_OPERATION_RATE_WINDOW":   "1m",
		"AUTH_RATE_LIMIT":                 "10",
		"AUTH_RATE_WINDOW":                "1m",
		"PROXY_HTTP_BIND":                 "127.0.0.1",
		"PROXY_HTTP_PORT":                 "8080",
		"API_HOST_PORT":                   "18080",
		"CONSOLE_HOST_PORT":               "13000",
	}
	return formatEnvFile(values), nil
}

func imageName(name, version string) string {
	return "ghcr.io/stealth-deplover/" + name + ":" + version
}

func mustParseURLScheme(raw string) string {
	parsed, _ := url.Parse(raw)
	if parsed == nil {
		return ""
	}
	return parsed.Scheme
}

func formatEnvFile(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by Stealth CLI. Keep this file private.\n")
	for _, key := range keys {
		builder.WriteString(key)
		builder.WriteByte('=')
		builder.WriteString(values[key])
		builder.WriteByte('\n')
	}
	return builder.String()
}

func readEnvFile(path string) (map[string]string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	values := make(map[string]string)
	for lineNumber, rawLine := range strings.Split(string(contents), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || !validEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return nil, fmt.Errorf("invalid config.env line %d", lineNumber+1)
		}
		values[key] = strings.Trim(value, " \t")
	}
	return values, nil
}

func validEnvKey(value string) bool {
	if value == "" {
		return false
	}
	for index, char := range value {
		if (char < 'A' || char > 'Z') && (char < 'a' || char > 'z') && (char < '0' || char > '9') && char != '_' || index == 0 && char >= '0' && char <= '9' {
			return false
		}
	}
	return true
}

func hasRequiredConfig(values map[string]string) bool {
	for _, key := range []string{
		"STEALTH_API_IMAGE",
		"STEALTH_WORKER_IMAGE",
		"STEALTH_MIGRATE_IMAGE",
		"STEALTH_CONSOLE_IMAGE",
		"POSTGRES_DB",
		"POSTGRES_USER",
		"POSTGRES_PASSWORD",
		"REDIS_PASSWORD",
		"FUNCTIONS_SECRET_KEY",
		"PUBLIC_APP_URL",
		"DOCKER_GID",
	} {
		if strings.TrimSpace(values[key]) == "" {
			return false
		}
	}
	return true
}

func configCheckDetail(path string, private bool) string {
	if private {
		return path + " (mode 0600)"
	}
	return path + " (expected mode 0600)"
}

func validLogService(service string) bool {
	switch service {
	case "api", "worker", "console", "proxy", "postgres", "redis", "migrate":
		return true
	default:
		return false
	}
}

func portsFromConfig(values map[string]string) localPorts {
	return localPorts{
		API:     portOrDefault(values["API_HOST_PORT"], "18080"),
		Console: portOrDefault(values["CONSOLE_HOST_PORT"], "13000"),
		Proxy:   portOrDefault(values["PROXY_HTTP_PORT"], "8080"),
	}
}

func portOrDefault(raw, fallback string) string {
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || value < 1 || value > 65535 {
		return fallback
	}
	return strconv.Itoa(value)
}

func (a *App) loadExistingPlan(layout InstallLayout) (*InstallPlan, error) {
	values, err := readEnvFile(layout.EnvFile)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", layout.EnvFile, err)
	}
	publicURL, err := validatePublicURL(values["PUBLIC_APP_URL"])
	if err != nil {
		return nil, fmt.Errorf("existing PUBLIC_APP_URL is invalid: %w", err)
	}
	version := readVersion(layout)
	if version == "" || version == "dev" {
		version, err = imageVersion(values["STEALTH_API_IMAGE"])
		if err != nil {
			return nil, fmt.Errorf("existing release version is unavailable: %w", err)
		}
	}
	if err := validateReleaseVersion(version); err != nil {
		return nil, fmt.Errorf("existing release version is invalid: %w", err)
	}
	gid, err := strconv.ParseUint(values["DOCKER_GID"], 10, 32)
	if err != nil {
		return nil, fmt.Errorf("existing DOCKER_GID is invalid")
	}
	return &InstallPlan{Layout: layout, Version: version, PublicURL: publicURL, DockerGID: uint32(gid), Existing: true}, nil
}

func imageVersion(image string) (string, error) {
	_, version, ok := strings.Cut(strings.TrimSpace(image), ":")
	if !ok || version == "" {
		return "", fmt.Errorf("image tag is missing")
	}
	return version, nil
}

func writePrivateFile(path, contents string) error {
	return writeAtomic(path, []byte(contents), 0600)
}

func writeAtomic(path string, contents []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".stealth-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}
