// Package installengine owns the idempotent installation primitives shared by
// the CLI and the browser setup service. UI layers select a plan and receive
// structured progress; this package owns files, Compose, and health checks.
package installengine

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const (
	defaultAssetBase = "https://raw.githubusercontent.com/Stealth-deplover/stealth"
	maxAssetSize     = 2 << 20
	lockFileName     = "install.lock"
)

// CommandRunner is the only process boundary the engine needs. The browser
// service injects the same runner as the CLI, but it never invokes the
// stealth executable itself.
type CommandRunner interface {
	Run(context.Context, string, io.Writer, io.Writer, string, ...string) error
	Output(context.Context, string, string, ...string) ([]byte, error)
}

// OSCommandRunner executes the Docker Compose commands selected by a plan.
// It is intentionally small so tests can assert the exact command surface.
type OSCommandRunner struct{}

func (OSCommandRunner) Run(ctx context.Context, dir string, stdout, stderr io.Writer, name string, args ...string) error {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	command.Stdout = stdout
	command.Stderr = stderr
	return command.Run()
}

func (OSCommandRunner) Output(ctx context.Context, dir, name string, args ...string) ([]byte, error) {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	return command.Output()
}

// Layout is the on-host installation boundary. The setup service receives a
// host bind mount at this exact root, which lets the same engine write the
// durable production files before handing Compose back to the host.
type Layout struct {
	Root             string
	EnvFile          string
	ComposeFile      string
	SetupComposeFile string
	ProxyFile        string
	VersionFile      string
	StateDir         string
}

func NewLayout(root string) (Layout, error) {
	root = strings.TrimSpace(root)
	if root == "" {
		return Layout{}, errors.New("installation root is required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve installation root: %w", err)
	}
	clean := filepath.Clean(abs)
	if clean == string(filepath.Separator) {
		return Layout{}, errors.New("refusing filesystem root as installation root")
	}
	return Layout{
		Root:             clean,
		EnvFile:          filepath.Join(clean, "config.env"),
		ComposeFile:      filepath.Join(clean, "compose.production.yaml"),
		SetupComposeFile: filepath.Join(clean, "compose.setup.yaml"),
		ProxyFile:        filepath.Join(clean, "console", "deploy", "nginx.conf"),
		VersionFile:      filepath.Join(clean, "VERSION"),
		StateDir:         filepath.Join(clean, "state"),
	}, nil
}

// Plan contains only installation decisions. Secrets are generated by the
// engine for a fresh plan or are supplied as already-rendered ConfigContents
// for a browser-confirmed plan.
type Plan struct {
	Layout             Layout
	Version            string
	PublicURL          string
	GitHubAppClientID  string
	DockerGID          uint32
	Existing           bool
	Setup              bool
	ExternalDatabase   bool
	ExternalRedis      bool
	Cloudflare         bool
	VerifyPublicURL    bool
	ConfigContents     string
	InternalAPIURL     string
	InternalConsoleURL string
	InternalProxyURL   string
}

type Step int

const (
	StepConfiguration Step = iota
	StepPull
	StepDependencies
	StepMigration
	StepServices
	StepVerify
)

var StepNames = []string{
	"Configuration and secrets",
	"Release images",
	"PostgreSQL and Redis",
	"Database migrations",
	"API, Worker, Console, and Proxy",
	"Health and readiness verification",
}

type Event struct {
	Step    string    `json:"step"`
	Status  string    `json:"status"`
	Message string    `json:"message,omitempty"`
	Error   string    `json:"error,omitempty"`
	At      time.Time `json:"at"`
}

type Options struct {
	Runner       CommandRunner
	HTTPClient   *http.Client
	AssetBaseURL string
	Output       io.Writer
	PollAttempts int
	PollInterval time.Duration
}

type Engine struct {
	runner       CommandRunner
	httpClient   *http.Client
	assetBaseURL string
	output       io.Writer
	pollAttempts int
	pollInterval time.Duration
}

func New(options Options) *Engine {
	runner := options.Runner
	if runner == nil {
		runner = OSCommandRunner{}
	}
	httpClient := options.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{Timeout: 20 * time.Second}
	}
	assetBaseURL := strings.TrimRight(strings.TrimSpace(options.AssetBaseURL), "/")
	if assetBaseURL == "" {
		assetBaseURL = defaultAssetBase
	}
	attempts := options.PollAttempts
	if attempts < 1 {
		attempts = 60
	}
	interval := options.PollInterval
	if interval <= 0 {
		interval = 2 * time.Second
	}
	output := options.Output
	if output == nil {
		output = io.Discard
	}
	return &Engine{runner: runner, httpClient: httpClient, assetBaseURL: assetBaseURL, output: output, pollAttempts: attempts, pollInterval: interval}
}

// Install executes every step while holding an OS-level lock. The lock is
// released on process exit, so a restarted setup service can safely resume a
// partial installation without manual lock-file cleanup.
func (e *Engine) Install(ctx context.Context, plan Plan, emit func(Event)) error {
	if e == nil {
		return errors.New("install engine is nil")
	}
	lock, err := acquireLock(plan.Layout.StateDir)
	if err != nil {
		return err
	}
	defer lock.Close()

	for step := StepConfiguration; step <= StepVerify; step++ {
		event := Event{Step: StepNames[step], Status: "started", At: time.Now().UTC()}
		if emit != nil {
			emit(event)
		}
		if err := e.RunStep(ctx, plan, step); err != nil {
			event.Status = "failed"
			event.Error = safeError(err)
			event.At = time.Now().UTC()
			if emit != nil {
				emit(event)
			}
			return err
		}
		event.Status = "succeeded"
		event.Message = "complete"
		event.At = time.Now().UTC()
		if emit != nil {
			emit(event)
		}
	}
	return nil
}

func (e *Engine) RunStep(ctx context.Context, plan Plan, step Step) error {
	switch step {
	case StepConfiguration:
		return e.Prepare(ctx, plan)
	case StepPull:
		return e.runCompose(ctx, plan, "pull")
	case StepDependencies:
		services := make([]string, 0, 2)
		if !plan.ExternalDatabase {
			services = append(services, "postgres")
		}
		if !plan.ExternalRedis {
			services = append(services, "redis")
		}
		if len(services) == 0 {
			return nil
		}
		return e.runCompose(ctx, plan, append([]string{"up", "-d"}, services...)...)
	case StepMigration:
		if plan.ExternalDatabase {
			return e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "migrate")
		}
		return e.runCompose(ctx, plan, "up", "migrate")
	case StepServices:
		services := []string{"api", "worker", "console", "proxy"}
		if plan.Setup {
			services = []string{"setup", "setup-console", "setup-proxy"}
		}
		if plan.Cloudflare {
			services = append(services, "cloudflared")
		}
		args := []string{"up", "-d"}
		if plan.ExternalDatabase || plan.ExternalRedis {
			args = append(args, "--no-deps")
		}
		args = append(args, services...)
		return e.runCompose(ctx, plan, args...)
	case StepVerify:
		return e.Wait(ctx, plan)
	default:
		return fmt.Errorf("unknown install step %d", step)
	}
}

func (e *Engine) Prepare(ctx context.Context, plan Plan) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if plan.Layout.Root == "" || plan.Layout.EnvFile == "" || plan.Layout.ComposeFile == "" {
		return errors.New("installation layout is incomplete")
	}
	if err := os.MkdirAll(plan.Layout.Root, 0o700); err != nil {
		return fmt.Errorf("create installation directory: %w", err)
	}
	if err := os.Chmod(plan.Layout.Root, 0o700); err != nil {
		return fmt.Errorf("protect installation directory: %w", err)
	}
	if err := os.MkdirAll(plan.Layout.StateDir, 0o700); err != nil {
		return fmt.Errorf("create state directory: %w", err)
	}
	if !plan.Existing {
		contents := plan.ConfigContents
		if strings.TrimSpace(contents) == "" {
			var err error
			contents, err = GenerateConfig(ConfigOptions{Version: plan.Version, PublicURL: plan.PublicURL, GitHubAppClientID: plan.GitHubAppClientID, DockerGID: plan.DockerGID, Setup: plan.Setup, InstallRoot: plan.Layout.Root})
			if err != nil {
				return fmt.Errorf("generate configuration: %w", err)
			}
		}
		if err := WritePrivateFile(plan.Layout.EnvFile, contents); err != nil {
			return fmt.Errorf("write configuration: %w", err)
		}
	} else if !FileIsPrivate(plan.Layout.EnvFile) {
		return errors.New("existing configuration permissions are too broad; expected mode 0600")
	}
	if err := e.ensureAsset(ctx, plan.Layout.ComposeFile, plan.Version, "compose.production.yaml", []byte("services:")); err != nil {
		return fmt.Errorf("prepare production Compose file: %w", err)
	}
	if plan.Setup && plan.Layout.SetupComposeFile != "" {
		if err := e.ensureAsset(ctx, plan.Layout.SetupComposeFile, plan.Version, "compose.setup.yaml", []byte("services:")); err != nil {
			return fmt.Errorf("prepare setup Compose file: %w", err)
		}
	}
	if err := e.ensureAsset(ctx, plan.Layout.ProxyFile, plan.Version, "console/deploy/nginx.conf", []byte("server {")); err != nil {
		return fmt.Errorf("prepare proxy configuration: %w", err)
	}
	if err := WriteAtomic(plan.Layout.VersionFile, []byte(strings.TrimSpace(plan.Version)+"\n"), 0o644); err != nil {
		return fmt.Errorf("write version file: %w", err)
	}
	return nil
}

func (e *Engine) ensureAsset(ctx context.Context, path, version, asset string, marker []byte) error {
	if FileExists(path) {
		return nil
	}
	if strings.TrimSpace(version) == "" {
		return errors.New("release version is required")
	}
	contents, err := e.fetchAsset(ctx, e.assetBaseURL+"/"+version+"/"+asset)
	if err != nil {
		return err
	}
	if !bytes.Contains(contents, marker) {
		return fmt.Errorf("downloaded asset %q is invalid", asset)
	}
	return WriteAtomic(path, contents, 0o644)
}

// Wait checks the host-visible service endpoints for CLI plans and the
// Compose-network endpoints for browser handoff plans. A public URL is only
// probed when the plan explicitly requests the final ingress check.
func (e *Engine) Wait(ctx context.Context, plan Plan) error {
	values, err := ReadEnvFile(plan.Layout.EnvFile)
	if err != nil {
		return fmt.Errorf("read installation configuration: %w", err)
	}
	apiURL := strings.TrimRight(plan.InternalAPIURL, "/")
	consoleURL := strings.TrimRight(plan.InternalConsoleURL, "/")
	proxyURL := strings.TrimRight(plan.InternalProxyURL, "/")
	if apiURL == "" {
		apiURL = "http://127.0.0.1:" + PortOrDefault(values["API_HOST_PORT"], "18080")
	}
	if consoleURL == "" {
		consoleURL = "http://127.0.0.1:" + PortOrDefault(values["CONSOLE_HOST_PORT"], "13000")
	}
	if proxyURL == "" {
		proxyURL = "http://127.0.0.1:" + PortOrDefault(values["PROXY_HTTP_PORT"], "8080")
	}
	endpoints := []string{apiURL + "/healthz", apiURL + "/readyz", apiURL + "/version", consoleURL + "/", proxyURL + "/"}
	if plan.VerifyPublicURL && strings.TrimRight(plan.PublicURL, "/") != "" {
		endpoints = append(endpoints, strings.TrimRight(plan.PublicURL, "/")+"/")
	}
	maxWait := time.Duration(e.pollAttempts)*e.pollInterval + 30*time.Second
	waitContext, cancel := context.WithTimeout(ctx, maxWait)
	defer cancel()
	for attempt := 0; attempt < e.pollAttempts; attempt++ {
		if err := waitContext.Err(); err != nil {
			return err
		}
		allReady := true
		for _, endpoint := range endpoints {
			status, requestErr := e.httpStatus(waitContext, endpoint)
			if requestErr != nil || status < 200 || status >= 300 {
				allReady = false
				break
			}
		}
		if allReady {
			return nil
		}
		if attempt+1 < e.pollAttempts {
			if err := waitInterval(waitContext, e.pollInterval); err != nil {
				return err
			}
		}
	}
	return fmt.Errorf("services did not become ready after %d checks", e.pollAttempts)
}

func (e *Engine) runCompose(ctx context.Context, plan Plan, args ...string) error {
	composeArgs := []string{"compose"}
	if plan.Cloudflare {
		composeArgs = append(composeArgs, "--profile", "cloudflare")
	}
	composeFile := plan.Layout.ComposeFile
	if plan.Setup && plan.Layout.SetupComposeFile != "" {
		composeFile = plan.Layout.SetupComposeFile
	}
	if strings.TrimSpace(composeFile) == "" {
		return errors.New("Compose file is required")
	}
	composeArgs = append(composeArgs, "--env-file", plan.Layout.EnvFile, "-f", composeFile)
	composeArgs = append(composeArgs, args...)
	if err := e.runner.Run(ctx, plan.Layout.Root, e.output, e.output, "docker", composeArgs...); err != nil {
		return fmt.Errorf("docker compose %v failed: %w", args, err)
	}
	return nil
}

func (e *Engine) fetchAsset(ctx context.Context, assetURL string) ([]byte, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, assetURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create asset request: %w", err)
	}
	response, err := e.httpClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("download asset: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download asset returned HTTP %d", response.StatusCode)
	}
	contents, err := io.ReadAll(io.LimitReader(response.Body, maxAssetSize+1))
	if err != nil {
		return nil, fmt.Errorf("read downloaded asset: %w", err)
	}
	if len(contents) > maxAssetSize {
		return nil, errors.New("downloaded asset is unexpectedly large")
	}
	return contents, nil
}

// RunCommand exposes the same process boundary used by installation steps for
// narrowly scoped lifecycle operations such as removing the exact temporary
// onboarding container. Callers must validate any resource name before
// passing it here; this method is not a general shell interface.
func (e *Engine) RunCommand(ctx context.Context, dir, name string, args ...string) error {
	if e == nil || e.runner == nil {
		return errors.New("install engine is not configured")
	}
	return e.runner.Run(ctx, dir, io.Discard, io.Discard, name, args...)
}

func (e *Engine) httpStatus(ctx context.Context, endpoint string) (int, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return 0, err
	}
	response, err := e.httpClient.Do(request)
	if err != nil {
		return 0, err
	}
	defer response.Body.Close()
	_, _ = io.Copy(io.Discard, io.LimitReader(response.Body, 4096))
	return response.StatusCode, nil
}

func waitInterval(ctx context.Context, interval time.Duration) error {
	if interval <= 0 {
		return nil
	}
	timer := time.NewTimer(interval)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func acquireLock(stateDir string) (*os.File, error) {
	if strings.TrimSpace(stateDir) == "" {
		return nil, errors.New("installation state directory is required")
	}
	if err := os.MkdirAll(stateDir, 0o700); err != nil {
		return nil, fmt.Errorf("create installation lock directory: %w", err)
	}
	lockPath := filepath.Join(stateDir, lockFileName)
	file, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("open installation lock: %w", err)
	}
	if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		_ = file.Close()
		if errors.Is(err, syscall.EWOULDBLOCK) {
			return nil, errors.New("another installation operation is already running")
		}
		return nil, fmt.Errorf("lock installation: %w", err)
	}
	return file, nil
}

func safeError(err error) string {
	if err == nil {
		return ""
	}
	// Compose errors are allowed to include service names and status codes, but
	// never copy a command's output into a browser event. The command runner is
	// configured with a discard writer by the HTTP composition root.
	message := strings.TrimSpace(err.Error())
	if len(message) > 240 {
		message = message[:240]
	}
	return message
}

// The small wrappers below are intentionally exported so the CLI can delete
// its duplicate file/configuration implementation while preserving its
// existing tests and operator behavior.
func FileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Mode()&os.ModeSymlink == 0
}

func FileIsPrivate(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Mode().Perm()&0o077 == 0
}

func WritePrivateFile(path, contents string) error {
	return WriteAtomic(path, []byte(contents), 0o600)
}

func WriteAtomic(path string, contents []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".stealth-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func ReadEnvFile(path string) (map[string]string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	values := make(map[string]string)
	for lineNumber, rawLine := range strings.Split(string(contents), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return nil, fmt.Errorf("invalid config.env line %d", lineNumber+1)
		}
		values[key] = strings.Trim(value, " \t")
	}
	return values, nil
}

func ValidEnvKey(value string) bool {
	if value == "" {
		return false
	}
	for index, character := range value {
		if (character < 'A' || character > 'Z') && (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '_' {
			return false
		}
		if index == 0 && character >= '0' && character <= '9' {
			return false
		}
	}
	return true
}

func FormatEnvFile(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by Stealth. Keep this file private.\n")
	for _, key := range keys {
		builder.WriteString(key)
		builder.WriteByte('=')
		builder.WriteString(values[key])
		builder.WriteByte('\n')
	}
	return builder.String()
}

func MergeEnv(base map[string]string, updates map[string]string) (string, error) {
	values := make(map[string]string, len(base)+len(updates))
	for key, value := range base {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	for key, value := range updates {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	return FormatEnvFile(values), nil
}

func PortOrDefault(raw, fallback string) string {
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || value < 1 || value > 65535 {
		return fallback
	}
	return strconv.Itoa(value)
}
