// Package installengine owns the idempotent installation primitives used by
// the host CLI. UI and setup API layers select or project state; this package
// owns files, Compose, and health checks without exposing a shell boundary to
// the browser.
package installengine

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/Stealth-deplover/stealth/internal/buildkitpki"
)

const (
	defaultAssetBase = "https://raw.githubusercontent.com/Stealth-deplover/stealth"
	maxAssetSize     = 2 << 20
	lockFileName     = "install.lock"
)

// ErrOperationInProgress lets a recovering worker distinguish lock ownership
// from an installation failure. A worker that loses the race leaves the
// durable run in installing so the lock owner can continue publishing state;
// a later process can resume it after a crash releases the OS lock.
var ErrOperationInProgress = errors.New("another installation operation is already running")

// CommandRunner is the only process boundary the host engine needs. The setup
// API does not construct an engine or receive a command runner.
type CommandRunner interface {
	Run(context.Context, string, io.Writer, io.Writer, string, ...string) error
	Output(context.Context, string, string, ...string) ([]byte, error)
}

// InputCommandRunner extends the process boundary for fixed trusted input.
// It is used when a narrow privileged host command must consume a validated
// release asset without reopening a user-writable source path.
type InputCommandRunner interface {
	RunInput(context.Context, string, io.Reader, io.Writer, io.Writer, string, ...string) error
}

// OSCommandRunner executes the Docker Compose commands selected by a plan.
// It is intentionally small so tests can assert the exact command surface.
type OSCommandRunner struct{}

func (OSCommandRunner) Run(ctx context.Context, dir string, stdout, stderr io.Writer, name string, args ...string) error {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	command.Stdout = stdout
	command.Stderr = stderr
	return command.Run()
}

func (OSCommandRunner) RunInput(ctx context.Context, dir string, stdin io.Reader, stdout, stderr io.Writer, name string, args ...string) error {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	command.Stdin = stdin
	command.Stdout = stdout
	command.Stderr = stderr
	return command.Run()
}

func (OSCommandRunner) Output(ctx context.Context, dir, name string, args ...string) ([]byte, error) {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	return command.Output()
}

// Layout is the on-host installation boundary. The host CLI writes durable
// production files and runs Compose from this root; the setup API only shares
// the separate encrypted state directory.
type Layout struct {
	Root                string
	EnvFile             string
	ComposeFile         string
	SetupComposeFile    string
	TelemetryDir        string
	ProxyFile           string
	TraefikDir          string
	TraefikStatic       string
	TraefikDynamic      string
	TraefikCore         string
	TraefikGenerated    string
	TraefikReloadMarker string
	VersionFile         string
	StateDir            string
	PrivateDir          string
	BuildKitPKIDir      string
}

func NewLayout(root string) (Layout, error) {
	root = strings.TrimSpace(root)
	if root == "" {
		return Layout{}, errors.New("installation root is required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve installation root: %w", err)
	}
	clean := filepath.Clean(abs)
	if clean == string(filepath.Separator) {
		return Layout{}, errors.New("refusing filesystem root as installation root")
	}
	return Layout{
		Root:                clean,
		EnvFile:             filepath.Join(clean, "config.env"),
		ComposeFile:         filepath.Join(clean, "compose.production.yaml"),
		SetupComposeFile:    filepath.Join(clean, "compose.setup.yaml"),
		TelemetryDir:        filepath.Join(clean, "telemetry"),
		ProxyFile:           filepath.Join(clean, "console", "deploy", "nginx.conf"),
		TraefikDir:          filepath.Join(clean, "traefik"),
		TraefikStatic:       filepath.Join(clean, "traefik", "traefik.yaml"),
		TraefikDynamic:      filepath.Join(clean, "traefik", "dynamic"),
		TraefikCore:         filepath.Join(clean, "traefik", "dynamic", "core.yaml"),
		TraefikGenerated:    filepath.Join(clean, "traefik", "dynamic", "generated"),
		TraefikReloadMarker: filepath.Join(clean, "traefik", "dynamic", ".reload.yaml"),
		VersionFile:         filepath.Join(clean, "VERSION"),
		StateDir:            filepath.Join(clean, "state"),
		PrivateDir:          filepath.Join(clean, "private"),
		BuildKitPKIDir:      filepath.Join(clean, "private", buildkitpki.DirectoryName),
	}, nil
}

// Plan contains only installation decisions. Secrets are generated by the
// engine for a fresh plan or are supplied as already-rendered ConfigContents
// for a browser-confirmed plan.
type Plan struct {
	Layout  Layout
	Version string
	// InstalledVersion is the release currently recorded by an existing
	// installation. Version is the target release for this operation. Keeping
	// both values lets managed configuration advance canonical image references
	// without overwriting operator-selected image overrides.
	InstalledVersion   string
	PublicURL          string
	GitHubAppClientID  string
	DockerGID          uint32
	Existing           bool
	Setup              bool
	ExternalDatabase   bool
	ExternalRedis      bool
	Cloudflare         bool
	VerifyPublicURL    bool
	IngressNetworkName string
	ConfigContents     string
	InternalAPIURL     string
	InternalConsoleURL string
	InternalProxyURL   string
}

type Step int

const (
	StepConfiguration Step = iota
	StepPull
	StepDependencies
	StepMigration
	StepServices
	StepVerify
)

var StepNames = []string{
	"Configuration and secrets",
	"Release images",
	"PostgreSQL and Redis",
	"Database migrations",
	"API, Worker, BuildKit, Console, Proxy, and Traefik",
	"Health and readiness verification",
}

type Event struct {
	Step    string    `json:"step"`
	Status  string    `json:"status"`
	Message string    `json:"message,omitempty"`
	Error   string    `json:"error,omitempty"`
	At      time.Time `json:"at"`
}

type Options struct {
	Runner       CommandRunner
	HTTPClient   *http.Client
	AssetBaseURL string
	Output       io.Writer
	PollAttempts int
	PollInterval time.Duration

	// BuildKitAppArmorProfilePath is injectable for tests. Production stores
	// the profile under AppArmor's system profile directory so it is loaded on
	// host boot as well as during installation.
	BuildKitAppArmorProfilePath string

	// ManagedAssets is intentionally supplied by the release binary, never by
	// CLI input. It lets the target release own its runtime asset manifest, so
	// a future release can add an asset without teaching the previous binary
	// about it first. A nil value selects this release's built-in manifest.
	ManagedAssets []ManagedAsset

	// MigrationHook is a test-only fault-injection seam. Production callers do
	// not set it; it exists so recovery is exercised after each durable
	// transaction boundary instead of relying on timing-sensitive SIGKILL tests.
	MigrationHook func(MigrationEvent) error
}

type Engine struct {
	runner              CommandRunner
	httpClient          *http.Client
	assetBaseURL        string
	output              io.Writer
	pollAttempts        int
	pollInterval        time.Duration
	appArmorProfilePath string
	managedAssets       []ManagedAsset
	migrationHook       func(MigrationEvent) error
}

func New(options Options) *Engine {
	runner := options.Runner
	if runner == nil {
		runner = OSCommandRunner{}
	}
	httpClient := options.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{Timeout: 20 * time.Second}
	}
	assetBaseURL := strings.TrimRight(strings.TrimSpace(options.AssetBaseURL), "/")
	if assetBaseURL == "" {
		assetBaseURL = defaultAssetBase
	}
	attempts := options.PollAttempts
	if attempts < 1 {
		attempts = 60
	}
	interval := options.PollInterval
	if interval <= 0 {
		interval = 2 * time.Second
	}
	output := options.Output
	if output == nil {
		output = io.Discard
	}
	appArmorProfilePath := strings.TrimSpace(options.BuildKitAppArmorProfilePath)
	if appArmorProfilePath == "" {
		appArmorProfilePath = BuildKitAppArmorProfilePath
	}
	managedAssets := options.ManagedAssets
	if managedAssets == nil {
		managedAssets = DefaultManagedAssets()
	}
	return &Engine{
		runner: runner, httpClient: httpClient, assetBaseURL: assetBaseURL, output: output,
		pollAttempts: attempts, pollInterval: interval, appArmorProfilePath: appArmorProfilePath,
		managedAssets: append([]ManagedAsset(nil), managedAssets...),
		migrationHook: options.MigrationHook,
	}
}

// Install executes every step while holding an OS-level lock. The lock is
// released on process exit, so a restarted host CLI can safely resume a
// partial installation without manual lock-file cleanup.
func (e *Engine) Install(ctx context.Context, plan Plan, emit func(Event)) error {
	if e == nil {
		return errors.New("install engine is nil")
	}
	lock, err := acquireLock(plan.Layout.StateDir)
	if err != nil {
		return err
	}
	defer lock.Close()
	return e.InstallLocked(ctx, plan, emit)
}

// InstallLocked executes every step after the caller has acquired the
// installation lock. It exists for the host orchestrator, which must hold the
// same lock while it claims the durable InstallRunID and performs handoff
// cleanup. Callers must not invoke this method without owning the lock for
// plan.Layout.StateDir.
func (e *Engine) InstallLocked(ctx context.Context, plan Plan, emit func(Event)) error {
	if e == nil {
		return errors.New("install engine is nil")
	}
	for step := StepConfiguration; step <= StepVerify; step++ {
		event := Event{Step: StepNames[step], Status: "started", At: time.Now().UTC()}
		if emit != nil {
			emit(event)
		}
		if err := e.RunStep(ctx, plan, step); err != nil {
			event.Status = "failed"
			event.Error = safeError(err)
			event.At = time.Now().UTC()
			if emit != nil {
				emit(event)
			}
			return err
		}
		event.Status = "succeeded"
		event.Message = "complete"
		event.At = time.Now().UTC()
		if emit != nil {
			emit(event)
		}
	}
	return nil
}

func (e *Engine) RunStep(ctx context.Context, plan Plan, step Step) error {
	switch step {
	case StepConfiguration:
		prepared, err := e.prepareInstallation(ctx, plan)
		if err != nil {
			return err
		}
		// Existing installations from the previous release may still have the
		// dynamic directory owned by the fixed worker UID. Run the target
		// release's narrow init service against the staged Compose file before
		// managed assets are activated, so an unprivileged host user can still
		// complete an upgrade without changing ownership itself.
		if !plan.Setup && plan.Existing {
			composePath, ok := prepared.assets.stagedAssetPath("compose.production.yaml")
			if !ok {
				return prepared.failCommit(errors.New("staged production Compose asset is missing"))
			}
			if err := e.runTraefikStateInit(ctx, plan, composePath, plan.Layout.Root); err != nil {
				return prepared.failCommit(err)
			}
		}
		if err := prepared.commit(plan); err != nil {
			return err
		}
		if err := e.runCompose(ctx, plan, "config", "--quiet"); err != nil {
			rollbackErr := prepared.rollback()
			return errors.Join(err, rollbackErr)
		}
		if err := prepared.composeValidated(); err != nil {
			if errors.Is(err, errMigrationProcessInterrupted) {
				return err
			}
			return errors.Join(err, prepared.rollback())
		}
		// From COMPOSE_VALIDATED onward the new release is coherent. If the
		// bounded backup publication is interrupted, the next lifecycle command
		// completes it forward rather than rolling valid target assets back.
		if err := prepared.finalize(); err != nil {
			return err
		}
		if !plan.Setup {
			if _, err := ensureBuildKitPKI(plan.Layout); err != nil {
				return fmt.Errorf("prepare BuildKit mutual TLS identity: %w", err)
			}
			return e.ensureBuildKitAppArmorProfile(ctx, plan)
		}
		return nil
	case StepPull:
		return e.runCompose(ctx, plan, "pull")
	case StepDependencies:
		if !plan.Setup {
			// StepServices may use --no-deps for external PostgreSQL/Redis.
			// Run all narrow ownership init services explicitly so that path
			// never bypasses persistent state preparation.
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "otelcol-state-init"); err != nil {
				return err
			}
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "telemetry-docker-logs-state-init"); err != nil {
				return err
			}
			if err := e.runTraefikStateInit(ctx, plan, plan.Layout.ComposeFile, ""); err != nil {
				return err
			}
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "cloudflare-setup-state-init"); err != nil {
				return fmt.Errorf("prepare Cloudflare legacy-state input: %w", err)
			}
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "cloudflare-state-init"); err != nil {
				return err
			}
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "buildkit-worker-credentials-init"); err != nil {
				return fmt.Errorf("prepare worker BuildKit client credentials: %w", err)
			}
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "buildkit-server-credentials-init"); err != nil {
				return fmt.Errorf("prepare BuildKit server credentials: %w", err)
			}
		}
		services := make([]string, 0, 3)
		if !plan.ExternalDatabase {
			services = append(services, "postgres")
		}
		if !plan.ExternalRedis {
			services = append(services, "redis")
		}
		if !plan.Setup {
			services = append(services, "clickhouse")
		}
		if len(services) == 0 {
			return nil
		}
		return e.runCompose(ctx, plan, append([]string{"up", "-d"}, services...)...)
	case StepMigration:
		if plan.ExternalDatabase {
			return e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "migrate")
		}
		return e.runCompose(ctx, plan, "up", "migrate")
	case StepServices:
		services := []string{"api", "worker", "console", "proxy", "traefik"}
		if plan.Setup {
			services = []string{"setup", "setup-console", "setup-proxy"}
		} else {
			if plan.Existing {
				// Compose does not notice file content changes inside named
				// credential volumes. Recreate both consumers after the
				// one-shot initializers refresh them, including repair after an
				// interrupted rotation.
				if err := e.runCompose(ctx, plan, "up", "-d", "--no-deps", "--force-recreate", "buildkit", "worker"); err != nil {
					return fmt.Errorf("restart BuildKit and worker after refreshing mutual TLS credentials: %w", err)
				}
			}
			services = append(services, "buildkit")
			services = append(services, "otel-collector", "telemetry-host", "telemetry-docker-logs", "telemetry-docker-proxy", "telemetry-docker")
		}
		if plan.Cloudflare {
			services = append(services, "cloudflared")
		}
		args := []string{"up", "-d"}
		if plan.ExternalDatabase || plan.ExternalRedis {
			args = append(args, "--no-deps")
		}
		args = append(args, services...)
		return e.runCompose(ctx, plan, args...)
	case StepVerify:
		return e.Wait(ctx, plan)
	default:
		return fmt.Errorf("unknown install step %d", step)
	}
}

// ManagedAsset identifies a release-owned runtime file. The manifest is
// compiled into the target release binary; callers cannot supply it through a
// command-line flag or a downloaded manifest.
type ManagedAsset struct {
	Path       string
	RemotePath string
	Marker     string

	setupOnly      bool
	productionOnly bool
	validate       func([]byte) error
	render         func([]byte, Plan) ([]byte, error)
}

// DefaultManagedAssets is this release's complete production runtime manifest.
// New releases extend this list in their own binary, which is why update
// invokes the verified target binary before replacing the installed CLI.
func DefaultManagedAssets() []ManagedAsset {
	return []ManagedAsset{
		{Path: "compose.production.yaml", RemotePath: "compose.production.yaml", Marker: "services:", validate: validateProductionComposeAsset},
		{Path: "buildkit/buildkitd.toml", RemotePath: "buildkit/buildkitd.toml", Marker: "rootless = true", productionOnly: true, validate: validateBuildKitConfigAsset},
		{Path: "buildkit/stealth-buildkit-rootless.apparmor", RemotePath: "buildkit/stealth-buildkit-rootless.apparmor", Marker: BuildKitAppArmorProfileName, productionOnly: true, validate: validateBuildKitAppArmorProfileAsset},
		{Path: "console/deploy/nginx.conf", RemotePath: "console/deploy/nginx.conf", Marker: "server {"},
		{Path: "traefik/traefik.yaml", RemotePath: "traefik/traefik.yaml", Marker: "entryPoints:", productionOnly: true, render: renderTraefikStaticAsset, validate: validateTraefikStaticAsset},
		{Path: "traefik/dynamic/core.yaml", RemotePath: "traefik/dynamic/core.yaml", Marker: "__STEALTH_PUBLIC_HOST__", productionOnly: true, render: renderTraefikCoreAsset, validate: validateTraefikCoreAsset},
		{Path: "traefik/dynamic/generated/.gitkeep", RemotePath: "traefik/dynamic/generated/.gitkeep", Marker: "Stealth route reconciler", productionOnly: true},
		{Path: "telemetry/otel-collector.yaml", RemotePath: "telemetry/otel-collector.yaml", Marker: "receivers:", validate: validateMainCollectorAsset},
		{Path: "telemetry/host-metrics.yaml", RemotePath: "telemetry/host-metrics.yaml", Marker: "hostmetrics:"},
		{Path: "telemetry/docker-logs.yaml", RemotePath: "telemetry/docker-logs.yaml", Marker: "file_log/docker:"},
		{Path: "telemetry/docker-stats.yaml", RemotePath: "telemetry/docker-stats.yaml", Marker: "docker_stats:"},
		{Path: "compose.setup.yaml", RemotePath: "compose.setup.yaml", Marker: "services:", setupOnly: true},
	}
}

type migrationPhase string

const (
	migrationPhasePrepared         migrationPhase = "PREPARED"
	migrationPhaseBackedUp         migrationPhase = "BACKED_UP"
	migrationPhaseAssetsActivated  migrationPhase = "ASSETS_ACTIVATED"
	migrationPhaseConfigActivated  migrationPhase = "CONFIG_ACTIVATED"
	migrationPhaseVersionActivated migrationPhase = "VERSION_ACTIVATED"
	migrationPhaseComposeValidated migrationPhase = "COMPOSE_VALIDATED"
	migrationPhaseFinalized        migrationPhase = "FINALIZED"
)

const (
	migrationEventBackupRenamed  migrationPhase = "BACKUP_RENAMED"
	migrationEventAssetActivated migrationPhase = "ASSET_ACTIVATED"
)

// MigrationEvent reports a durable migration boundary to the test-only fault
// injection hook. A hook returning errMigrationProcessInterrupted models a
// hard process stop: it deliberately leaves the journal for the next process.
type MigrationEvent struct {
	Phase migrationPhase
	Asset string
	Index int
	Total int
}

var errMigrationProcessInterrupted = errors.New("managed asset migration interrupted")

type stagedManagedAsset struct {
	spec       ManagedAsset
	targetPath string
	stagePath  string
	backupPath string
	existed    bool
	backedUp   bool
	installed  bool
}

const managedAssetPendingFile = "managed-assets.pending"

type managedAssetRecoveryManifest struct {
	TransactionID   string                      `json:"transaction_id"`
	TargetVersion   string                      `json:"target_version"`
	OriginalVersion string                      `json:"original_version"`
	BackupDir       string                      `json:"backup_dir"`
	StageDir        string                      `json:"stage_dir"`
	Phase           migrationPhase              `json:"phase"`
	Assets          []managedAssetRecoveryEntry `json:"assets"`
	Config          managedAssetRecoveryFile    `json:"config"`
	Version         managedAssetRecoveryFile    `json:"version"`
}

type managedAssetRecoveryEntry struct {
	RelativePath string `json:"relative_path"`
	Existed      bool   `json:"existed"`
}

type managedAssetRecoveryFile struct {
	Existed bool   `json:"existed"`
	Backup  string `json:"backup,omitempty"`
	Mode    uint32 `json:"mode,omitempty"`
}

// managedAssetMigration stages the complete release-managed runtime set before
// changing the installation. Existing managed files are moved into one
// bounded recovery set, never copied with secrets, and restored if a later
// commit step or Compose validation fails.
type managedAssetMigration struct {
	layout         Layout
	stageDir       string
	backupDir      string
	assets         []stagedManagedAsset
	allowedPaths   map[string]struct{}
	hook           func(MigrationEvent) error
	manifest       managedAssetRecoveryManifest
	journalWritten bool
}

func (m *managedAssetMigration) stagedAssetPath(relativePath string) (string, bool) {
	if m == nil {
		return "", false
	}
	for _, asset := range m.assets {
		if asset.spec.Path == relativePath {
			return asset.stagePath, true
		}
	}
	return "", false
}

type preparedInstallation struct {
	layout              Layout
	assets              *managedAssetMigration
	originalEnv         []byte
	originalEnvExists   bool
	newEnv              []byte
	originalVersion     []byte
	originalVersionSet  bool
	originalVersionMode os.FileMode
}

func (e *Engine) Prepare(ctx context.Context, plan Plan) error {
	// Keep this exported preparation entry point subject to the same durable
	// transaction boundary as the lifecycle step. No caller can finalize a
	// managed-asset journal without successful `docker compose config --quiet`.
	return e.RunStep(ctx, plan, StepConfiguration)
}

// prepareInstallation downloads and validates the full managed asset set but
// does not publish it until commit. RunStep uses the returned transaction to
// roll the files back when docker compose config validation fails.
func (e *Engine) prepareInstallation(ctx context.Context, plan Plan) (*preparedInstallation, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if plan.Layout.Root == "" || plan.Layout.EnvFile == "" || plan.Layout.ComposeFile == "" {
		return nil, errors.New("installation layout is incomplete")
	}
	if err := ValidateReleaseVersion(strings.TrimSpace(plan.Version)); err != nil {
		return nil, err
	}
	if err := validateInstallRootBeforeCreation(plan.Layout.Root); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(plan.Layout.Root, 0o700); err != nil {
		return nil, fmt.Errorf("create installation directory: %w", err)
	}
	if err := os.Chmod(plan.Layout.Root, 0o700); err != nil {
		return nil, fmt.Errorf("protect installation directory: %w", err)
	}
	// Setup state is shared by the host CLI and the root setup container. The
	// setgid directory preserves the host operator's group on files atomically
	// replaced by the container, while the state payload remains group-private.
	stateDirectoryMode := os.FileMode(0o770) | os.ModeSetgid
	if err := os.MkdirAll(plan.Layout.StateDir, stateDirectoryMode); err != nil {
		return nil, fmt.Errorf("create state directory: %w", err)
	}
	if err := os.Chmod(plan.Layout.StateDir, stateDirectoryMode); err != nil {
		return nil, fmt.Errorf("protect state directory: %w", err)
	}
	prepared := &preparedInstallation{
		layout: plan.Layout,
	}
	var originalValues map[string]string
	generatedConfig := false
	if contents, err := os.ReadFile(plan.Layout.VersionFile); err == nil {
		prepared.originalVersion = contents
		prepared.originalVersionSet = true
		if info, statErr := os.Stat(plan.Layout.VersionFile); statErr == nil {
			prepared.originalVersionMode = info.Mode().Perm()
		} else {
			return nil, fmt.Errorf("inspect existing version: %w", statErr)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("read existing version: %w", err)
	}
	if plan.Existing {
		if !FileIsPrivate(plan.Layout.EnvFile) {
			return nil, errors.New("existing configuration permissions are too broad; expected mode 0600")
		}
		contents, err := os.ReadFile(plan.Layout.EnvFile)
		if err != nil {
			return nil, fmt.Errorf("read existing configuration: %w", err)
		}
		values, err := ReadEnvFile(plan.Layout.EnvFile)
		if err != nil {
			return nil, fmt.Errorf("parse existing configuration: %w", err)
		}
		originalValues = make(map[string]string, len(values))
		for key, value := range values {
			originalValues[key] = value
		}
		installedVersion := strings.TrimSpace(plan.InstalledVersion)
		if installedVersion == "" && prepared.originalVersionSet {
			installedVersion = strings.TrimSpace(string(prepared.originalVersion))
			if err := ValidateReleaseVersion(installedVersion); err != nil {
				return nil, fmt.Errorf("existing VERSION is invalid: %w", err)
			}
		}
		if installedVersion == "" {
			installedVersion = strings.TrimSpace(plan.Version)
		}
		migrated, err := MigrateReleaseConfig(values, plan.Version, installedVersion)
		if err != nil {
			return nil, fmt.Errorf("prepare existing configuration migration: %w", err)
		}
		prepared.originalEnv = contents
		prepared.originalEnvExists = true
		prepared.newEnv = []byte(migrated)
	} else {
		contents := plan.ConfigContents
		if strings.TrimSpace(contents) == "" {
			generatedConfig = true
			var err error
			appArmorProfile, profileErr := DetectBuildKitAppArmorProfile()
			if profileErr != nil {
				return nil, fmt.Errorf("detect BuildKit AppArmor requirements: %w", profileErr)
			}
			contents, err = GenerateConfig(ConfigOptions{
				Version: plan.Version, PublicURL: plan.PublicURL, GitHubAppClientID: plan.GitHubAppClientID,
				DockerGID: plan.DockerGID, Setup: plan.Setup, InstallRoot: plan.Layout.Root,
				IngressNetworkName: plan.IngressNetworkName, AppsBuildKitAppArmorProfile: appArmorProfile,
			})
			if err != nil {
				return nil, fmt.Errorf("generate configuration: %w", err)
			}
		}
		prepared.newEnv = []byte(contents)
	}
	if !plan.Setup {
		values, err := ParseEnvContents(string(prepared.newEnv))
		if err != nil {
			return nil, fmt.Errorf("parse prepared configuration: %w", err)
		}
		if generatedConfig {
			// GenerateConfig writes complete defaults so it can also be used as a
			// standalone config generator. For a fresh install, however, those
			// values are installer defaults rather than an operator's explicit
			// addressing choice; let collision-aware selection replace them.
			for _, key := range ingressNetworkEnvKeys {
				delete(values, key)
			}
		}
		if originalValues == nil {
			originalValues = values
		}
		ingress, err := e.resolveIngressNetworkConfig(ctx, plan, values, originalValues)
		if err != nil {
			return nil, fmt.Errorf("prepare ingress network configuration: %w", err)
		}
		if previous, previousErr := ingressNetworkConfigFromValues(originalValues); previousErr == nil && previous.trustedProxyCIDR() != ingress.trustedProxyCIDR() {
			// The previous peer was installer-derived whenever automatic subnet
			// selection or legacy-network adoption changes it. Remove only that
			// exact generated entry; all other operator proxy CIDRs survive.
			values["TRUSTED_PROXY_CIDRS"] = removeTrustedProxyCIDR(values["TRUSTED_PROXY_CIDRS"], previous.trustedProxyCIDR())
		}
		setIngressNetworkValues(values, ingress)
		trustedProxy := ensureTraefikTrustedProxyCIDR(values["TRUSTED_PROXY_CIDRS"], values["STEALTH_NETWORK_SUBNET"], ingress.trustedProxyCIDR())
		if trustedProxy != strings.TrimSpace(values["TRUSTED_PROXY_CIDRS"]) {
			values["TRUSTED_PROXY_CIDRS"] = trustedProxy
		}
		prepared.newEnv = []byte(FormatEnvFile(values))
	}
	assetPlan := plan
	assetPlan.ConfigContents = string(prepared.newEnv)
	assets, err := e.stageManagedAssets(ctx, assetPlan)
	if err != nil {
		return nil, err
	}
	prepared.assets = assets
	if !plan.Setup {
		if err := ensureTraefikDirectories(plan.Layout); err != nil {
			return nil, err
		}
	}
	return prepared, nil
}

func validateInstallRootBeforeCreation(root string) error {
	clean := filepath.Clean(strings.TrimSpace(root))
	if clean == "" || clean == string(filepath.Separator) {
		return errors.New("refusing filesystem root as installation directory")
	}
	info, err := os.Lstat(clean)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect installation directory: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return fmt.Errorf("installation directory %q is not a normal directory", clean)
	}
	return nil
}

func (p *preparedInstallation) commit(plan Plan) error {
	if p == nil || p.assets == nil {
		return errors.New("prepared installation is incomplete")
	}
	if err := p.assets.commit(plan, p.originalEnv, p.originalEnvExists, p.originalVersion, p.originalVersionSet, p.originalVersionMode); err != nil {
		return err
	}
	if err := WritePrivateFile(p.layout.EnvFile, string(p.newEnv)); err != nil {
		return p.failCommit(fmt.Errorf("write configuration: %w", err))
	}
	if err := p.assets.transition(migrationPhaseConfigActivated); err != nil {
		return p.failCommit(err)
	}
	if err := WriteAtomic(p.layout.VersionFile, []byte(strings.TrimSpace(plan.Version)+"\n"), 0o644); err != nil {
		return p.failCommit(fmt.Errorf("write version file: %w", err))
	}
	if err := p.assets.transition(migrationPhaseVersionActivated); err != nil {
		return p.failCommit(err)
	}
	return nil
}

func (p *preparedInstallation) failCommit(cause error) error {
	if errors.Is(cause, errMigrationProcessInterrupted) {
		return cause
	}
	return errors.Join(cause, p.rollback())
}

func (p *preparedInstallation) rollback() error {
	if p == nil {
		return nil
	}
	if p.assets == nil {
		return nil
	}
	return p.assets.rollback()
}

func (p *preparedInstallation) composeValidated() error {
	if p == nil || p.assets == nil {
		return errors.New("prepared installation is incomplete")
	}
	return p.assets.transition(migrationPhaseComposeValidated)
}

func (p *preparedInstallation) finalize() error {
	if p == nil || p.assets == nil {
		return nil
	}
	return p.assets.finalize()
}

func (e *Engine) managedAssetSpecs(plan Plan) []ManagedAsset {
	assets := make([]ManagedAsset, 0, len(e.managedAssets))
	for _, asset := range e.managedAssets {
		if asset.productionOnly && plan.Setup {
			continue
		}
		if asset.setupOnly && (plan.Layout.SetupComposeFile == "" || (!plan.Setup && !(plan.Existing && FileExists(plan.Layout.SetupComposeFile)))) {
			continue
		}
		assets = append(assets, asset)
	}
	return assets
}

func (e *Engine) stageManagedAssets(ctx context.Context, plan Plan) (*managedAssetMigration, error) {
	assets := e.managedAssetSpecs(plan)
	allowedPaths := make(map[string]struct{}, len(assets))
	for _, asset := range assets {
		if !validManagedAssetPath(asset.Path) {
			return nil, fmt.Errorf("managed asset path %q is invalid", asset.Path)
		}
		allowedPaths[asset.Path] = struct{}{}
	}
	if err := recoverInterruptedManagedAssetMigration(plan.Layout, allowedPaths); err != nil {
		return nil, fmt.Errorf("recover interrupted managed asset migration: %w", err)
	}
	stageDir, err := os.MkdirTemp(plan.Layout.StateDir, ".stealth-managed-assets-")
	if err != nil {
		return nil, fmt.Errorf("create managed asset staging directory: %w", err)
	}
	migration := &managedAssetMigration{
		layout:       plan.Layout,
		stageDir:     stageDir,
		allowedPaths: allowedPaths,
		hook:         e.migrationHook,
	}
	cleanup := func() {
		_ = os.RemoveAll(stageDir)
	}
	for _, spec := range assets {
		contents, err := e.fetchAsset(ctx, e.assetBaseURL+"/"+strings.TrimSpace(plan.Version)+"/"+spec.RemotePath)
		if err != nil {
			cleanup()
			return nil, fmt.Errorf("download managed asset %q: %w", spec.RemotePath, err)
		}
		if !bytes.Contains(contents, []byte(spec.Marker)) {
			cleanup()
			return nil, fmt.Errorf("downloaded asset %q is invalid", spec.RemotePath)
		}
		if spec.render != nil {
			contents, err = spec.render(contents, plan)
			if err != nil {
				cleanup()
				return nil, fmt.Errorf("render managed asset %q: %w", spec.RemotePath, err)
			}
		}
		if spec.validate != nil {
			if err := spec.validate(contents); err != nil {
				cleanup()
				return nil, fmt.Errorf("downloaded asset %q failed validation: %w", spec.RemotePath, err)
			}
		}
		stagePath := filepath.Join(stageDir, filepath.FromSlash(spec.Path))
		if err := WriteAtomic(stagePath, contents, 0o644); err != nil {
			cleanup()
			return nil, fmt.Errorf("stage managed asset %q: %w", spec.RemotePath, err)
		}
		migration.assets = append(migration.assets, stagedManagedAsset{
			spec:       spec,
			targetPath: filepath.Join(plan.Layout.Root, filepath.FromSlash(spec.Path)),
			stagePath:  stagePath,
		})
	}
	return migration, nil
}

// recoverInterruptedManagedAssetMigration is deliberately rollback-first until
// Compose validation has been durably recorded. That gives a restarted CLI
// exactly two externally visible states: the complete old release, or a
// complete, Compose-validated new release whose final cleanup can be finished.
func recoverInterruptedManagedAssetMigration(layout Layout, allowedPaths map[string]struct{}) error {
	pendingPath := filepath.Join(layout.StateDir, managedAssetPendingFile)
	info, err := os.Lstat(pendingPath)
	if errors.Is(err, os.ErrNotExist) {
		return removeStaleManagedAssetTransactions(layout)
	}
	if err != nil {
		return fmt.Errorf("inspect managed asset recovery journal: %w", err)
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("managed asset recovery journal is not a regular file")
	}
	contents, err := os.ReadFile(pendingPath)
	if err != nil {
		return fmt.Errorf("read managed asset recovery journal: %w", err)
	}
	var manifest managedAssetRecoveryManifest
	if err := json.Unmarshal(contents, &manifest); err != nil {
		return fmt.Errorf("parse managed asset recovery journal: %w", err)
	}
	if err := validateManagedAssetRecoveryManifest(manifest, allowedPaths); err != nil {
		return err
	}
	if manifest.Phase == migrationPhaseComposeValidated || manifest.Phase == migrationPhaseFinalized {
		if err := finalizeRecoveredManagedAssetMigration(layout, manifest); err != nil {
			return err
		}
	} else if err := rollbackManagedAssetMigration(layout, manifest); err != nil {
		return err
	}
	return removeStaleManagedAssetTransactions(layout)
}

func validateManagedAssetRecoveryManifest(manifest managedAssetRecoveryManifest, allowedPaths map[string]struct{}) error {
	if strings.TrimSpace(manifest.TransactionID) == "" || strings.ContainsAny(manifest.TransactionID, `/\\`) {
		return errors.New("managed asset recovery journal contains an invalid transaction id")
	}
	if err := ValidateReleaseVersion(manifest.TargetVersion); err != nil {
		return fmt.Errorf("managed asset recovery journal contains an invalid target version: %w", err)
	}
	if manifest.OriginalVersion != "" {
		if err := ValidateReleaseVersion(manifest.OriginalVersion); err != nil {
			return fmt.Errorf("managed asset recovery journal contains an invalid original version: %w", err)
		}
	}
	if !validManagedTransactionDirectory(manifest.BackupDir, ".stealth-managed-backup-") || !validManagedTransactionDirectory(manifest.StageDir, ".stealth-managed-assets-") {
		return errors.New("managed asset recovery journal contains an invalid transaction path")
	}
	switch manifest.Phase {
	case migrationPhasePrepared, migrationPhaseBackedUp, migrationPhaseAssetsActivated, migrationPhaseConfigActivated, migrationPhaseVersionActivated, migrationPhaseComposeValidated, migrationPhaseFinalized:
	default:
		return fmt.Errorf("managed asset recovery journal contains an unknown phase %q", manifest.Phase)
	}
	seen := make(map[string]struct{}, len(manifest.Assets))
	for _, entry := range manifest.Assets {
		if !validManagedAssetPath(entry.RelativePath) {
			return fmt.Errorf("managed asset recovery journal contains an invalid path %q", entry.RelativePath)
		}
		if _, ok := allowedPaths[entry.RelativePath]; !ok {
			return fmt.Errorf("managed asset recovery journal contains a path unknown to this release %q", entry.RelativePath)
		}
		if _, ok := seen[entry.RelativePath]; ok {
			return fmt.Errorf("managed asset recovery journal contains duplicate path %q", entry.RelativePath)
		}
		seen[entry.RelativePath] = struct{}{}
	}
	for _, file := range []managedAssetRecoveryFile{manifest.Config, manifest.Version} {
		if file.Existed && (file.Backup == "" || filepath.Base(file.Backup) != file.Backup) {
			return errors.New("managed asset recovery journal contains an invalid state backup path")
		}
	}
	return nil
}

func validManagedTransactionDirectory(value, prefix string) bool {
	return filepath.Base(value) == value && strings.HasPrefix(value, prefix) && !strings.ContainsAny(value, `/\\`)
}

func validManagedAssetPath(relativePath string) bool {
	if relativePath == "" || filepath.ToSlash(filepath.Clean(relativePath)) != relativePath {
		return false
	}
	return !strings.HasPrefix(relativePath, "../") && !strings.Contains(relativePath, "//")
}

func rollbackManagedAssetMigration(layout Layout, manifest managedAssetRecoveryManifest) error {
	backupDir := filepath.Join(layout.StateDir, manifest.BackupDir)
	if err := ensurePrivateManagedDirectory(backupDir); err != nil {
		return fmt.Errorf("inspect interrupted managed asset recovery set: %w", err)
	}
	for index := len(manifest.Assets) - 1; index >= 0; index-- {
		entry := manifest.Assets[index]
		targetPath := filepath.Join(layout.Root, filepath.FromSlash(entry.RelativePath))
		if !entry.Existed {
			if err := removeManagedAssetTarget(targetPath); err != nil {
				return fmt.Errorf("remove partially activated managed asset %q: %w", entry.RelativePath, err)
			}
			continue
		}
		sourcePath := filepath.Join(backupDir, filepath.FromSlash(entry.RelativePath))
		if sourceInfo, err := os.Lstat(sourcePath); errors.Is(err, os.ErrNotExist) {
			// PREPARED is recorded before the first source rename. Until the
			// backup phase is durable, an untouched regular target is the old
			// authoritative file.
			if manifest.Phase != migrationPhasePrepared {
				return fmt.Errorf("recover previous managed asset %q: backup is missing", entry.RelativePath)
			}
			if err := ensureRegularManagedAsset(targetPath); err != nil {
				return fmt.Errorf("recover previous managed asset %q: %w", entry.RelativePath, err)
			}
			continue
		} else if err != nil {
			return fmt.Errorf("recover previous managed asset %q: %w", entry.RelativePath, err)
		} else if !sourceInfo.Mode().IsRegular() || sourceInfo.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("recover previous managed asset %q: backup is not a regular file", entry.RelativePath)
		}
		if err := removeManagedAssetTarget(targetPath); err != nil {
			return fmt.Errorf("clear interrupted managed asset %q: %w", entry.RelativePath, err)
		}
		if err := os.MkdirAll(filepath.Dir(targetPath), 0o700); err != nil {
			return fmt.Errorf("prepare managed asset recovery path %q: %w", entry.RelativePath, err)
		}
		if err := renameAndSync(sourcePath, targetPath); err != nil {
			return fmt.Errorf("restore managed asset %q: %w", entry.RelativePath, err)
		}
	}
	if err := restoreManagedStateFile(layout.EnvFile, backupDir, manifest.Config, 0o600); err != nil {
		return fmt.Errorf("restore config.env: %w", err)
	}
	if err := restoreManagedStateFile(layout.VersionFile, backupDir, manifest.Version, 0o644); err != nil {
		return fmt.Errorf("restore VERSION: %w", err)
	}
	if err := removeAllAndSync(backupDir); err != nil {
		return fmt.Errorf("remove recovered managed asset set: %w", err)
	}
	if err := removeAllAndSync(filepath.Join(layout.StateDir, manifest.StageDir)); err != nil {
		return fmt.Errorf("remove recovered managed asset staging set: %w", err)
	}
	if err := removeAndSync(filepath.Join(layout.StateDir, managedAssetPendingFile)); err != nil {
		return fmt.Errorf("remove managed asset recovery journal: %w", err)
	}
	return nil
}

func publishManagedAssetRecoverySet(layout Layout, manifest managedAssetRecoveryManifest) error {
	backupDir := filepath.Join(layout.StateDir, manifest.BackupDir)
	previous := filepath.Join(layout.StateDir, "managed-assets.previous")
	if info, err := os.Lstat(backupDir); err == nil {
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("completed managed asset recovery set is not a directory")
		}
		if err := removeAllAndSync(previous); err != nil {
			return fmt.Errorf("replace previous managed asset recovery set: %w", err)
		}
		if err := renameAndSync(backupDir, previous); err != nil {
			return fmt.Errorf("publish managed asset recovery set: %w", err)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect completed managed asset recovery set: %w", err)
	} else if info, previousErr := os.Lstat(previous); previousErr != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("completed managed asset recovery set is missing")
	}
	if err := removeAllAndSync(filepath.Join(layout.StateDir, manifest.StageDir)); err != nil {
		return fmt.Errorf("remove completed managed asset staging set: %w", err)
	}
	return nil
}

func finalizeRecoveredManagedAssetMigration(layout Layout, manifest managedAssetRecoveryManifest) error {
	if err := publishManagedAssetRecoverySet(layout, manifest); err != nil {
		return err
	}
	if manifest.Phase != migrationPhaseFinalized {
		manifest.Phase = migrationPhaseFinalized
		contents, err := json.Marshal(manifest)
		if err != nil {
			return fmt.Errorf("encode completed managed asset recovery journal: %w", err)
		}
		if err := WriteAtomic(filepath.Join(layout.StateDir, managedAssetPendingFile), contents, 0o600); err != nil {
			return fmt.Errorf("record completed managed asset recovery journal: %w", err)
		}
	}
	if err := removeAndSync(filepath.Join(layout.StateDir, managedAssetPendingFile)); err != nil {
		return fmt.Errorf("remove completed managed asset recovery journal: %w", err)
	}
	return nil
}

func restoreManagedStateFile(targetPath, backupDir string, state managedAssetRecoveryFile, fallbackMode os.FileMode) error {
	if !state.Existed {
		return removeAndSync(targetPath)
	}
	backupPath := filepath.Join(backupDir, state.Backup)
	info, err := os.Lstat(backupPath)
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("state backup is not a regular file")
	}
	contents, err := os.ReadFile(backupPath)
	if err != nil {
		return err
	}
	mode := os.FileMode(state.Mode)
	if mode == 0 {
		mode = fallbackMode
	}
	return WriteAtomic(targetPath, contents, mode)
}

func ensurePrivateManagedDirectory(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		return err
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("not a directory")
	}
	return nil
}

func ensureRegularManagedAsset(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("target is not a regular file")
	}
	return nil
}

func removeStaleManagedAssetTransactions(layout Layout) error {
	entries, err := os.ReadDir(layout.StateDir)
	if err != nil {
		return fmt.Errorf("inspect managed asset staging directory: %w", err)
	}
	for _, entry := range entries {
		if !strings.HasPrefix(entry.Name(), ".stealth-managed-assets-") && !strings.HasPrefix(entry.Name(), ".stealth-managed-backup-") {
			continue
		}
		if err := removeAllAndSync(filepath.Join(layout.StateDir, entry.Name())); err != nil {
			return fmt.Errorf("remove stale managed asset transaction %q: %w", entry.Name(), err)
		}
	}
	return nil
}

func removeManagedAssetTarget(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("target is not a regular file")
	}
	return removeAndSync(path)
}

func renameAndSync(source, target string) error {
	if err := os.Rename(source, target); err != nil {
		return err
	}
	if err := syncDirectory(filepath.Dir(source)); err != nil {
		return err
	}
	if filepath.Dir(source) != filepath.Dir(target) {
		if err := syncDirectory(filepath.Dir(target)); err != nil {
			return err
		}
	}
	return nil
}

func removeAndSync(path string) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return syncDirectory(filepath.Dir(path))
}

func removeAllAndSync(path string) error {
	if err := os.RemoveAll(path); err != nil {
		return err
	}
	return syncDirectory(filepath.Dir(path))
}

func syncDirectory(path string) error {
	directory, err := os.Open(path)
	if err != nil {
		return err
	}
	defer directory.Close()
	return directory.Sync()
}

func validateProductionComposeAsset(contents []byte) error {
	for _, marker := range []string{
		"  traefik:",
		"  buildkit-worker-credentials-init:",
		"  buildkit-server-credentials-init:",
		"  buildkit:",
		"  traefik-state-init:",
		"  cloudflare-setup-state-init:",
		"  cloudflare-state-init:",
		"  otel-collector:",
		"  telemetry-host:",
		"  telemetry-docker-logs:",
		"  telemetry-docker:",
		"  telemetry-docker-proxy:",
		"  telemetry_ingest:",
		"  app_build:",
		"  buildkit_worker_credentials:",
		"  buildkit_server_credentials:",
		"  cloudflare_setup_state_input:",
		"  buildkit_server_credentials:\n    name: \"${COMPOSE_PROJECT_NAME:-stealth}_app_buildkit_server_credentials\"\n  cloudflare_setup_state_input:\n    name: \"${COMPOSE_PROJECT_NAME:-stealth}_cloudflare_setup_state_input\"",
	} {
		if !bytes.Contains(contents, []byte(marker)) {
			return fmt.Errorf("missing current production Compose marker %q", marker)
		}
	}
	text := string(contents)
	service := productionServiceBlock(text, "buildkit")
	if service == "" {
		return errors.New("missing dedicated App BuildKit service")
	}
	for _, required := range []string{
		"image: " + defaultBuildKitImage,
		"user: \"1000:1000\"", "read_only: true", "seccomp=unconfined",
		"apparmor=${APPS_BUILDKIT_APPARMOR_PROFILE:-unconfined}", "systempaths=unconfined", "buildkit_state:/home/user/.local/share/buildkit",
		"networks: [app_build]", "buildkit/buildkitd.toml:/etc/buildkit/buildkitd.toml:ro",
		"buildkit_server_credentials:/run/secrets/stealth-buildkit:ro",
		"tcp://0.0.0.0:1234", "--config", "/etc/buildkit/buildkitd.toml",
		"--tlscacert", "/run/secrets/stealth-buildkit/ca.pem",
		"--tlscert", "/run/secrets/stealth-buildkit/health-client-cert.pem",
		"--tlskey", "/run/secrets/stealth-buildkit/health-client-key.pem", "debug", "workers",
	} {
		if !strings.Contains(service, required) {
			return fmt.Errorf("App BuildKit service is missing required setting %q", required)
		}
	}
	for _, forbidden := range []string{
		"privileged:", "network_mode: host", "pid: host", "ipc: host", "/var/run/docker.sock",
		"ports:", "stealth:", "telemetry_store:", "ingress_control_db:", "stealth_storage:", "app_build_staging:",
		"state/buildkit-mtls", "buildkit_worker_credentials:",
	} {
		if strings.Contains(service, forbidden) {
			return fmt.Errorf("App BuildKit service contains forbidden setting %q", forbidden)
		}
	}
	worker := productionServiceBlock(text, "worker")
	if worker == "" || !strings.Contains(worker, "buildkit_worker_credentials:/run/secrets/stealth-buildkit:ro") {
		return errors.New("worker must mount only its read-only BuildKit client credentials volume")
	}
	if strings.Contains(worker, "buildkit-mtls") || strings.Contains(worker, "buildkit_server_credentials:") || strings.Contains(worker, "ca-key.pem") {
		return errors.New("worker must not mount host PKI files or BuildKit server credentials")
	}
	workerInit := productionServiceBlock(text, "buildkit-worker-credentials-init")
	serverInit := productionServiceBlock(text, "buildkit-server-credentials-init")
	for name, block := range map[string]string{"worker": workerInit, "BuildKit": serverInit} {
		if block == "" || !strings.Contains(block, "network_mode: none") || !strings.Contains(block, "restart: \"no\"") ||
			!strings.Contains(block, "cap_drop: [ALL]") || !strings.Contains(block, "cap_add: [CHOWN, DAC_OVERRIDE]") {
			return fmt.Errorf("%s BuildKit credential initializer must be a networkless one-shot with only copy and ownership capabilities", name)
		}
	}
	for _, required := range []string{
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/ca-cert.pem:/input/ca.pem:ro",
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/worker/cert.pem:/input/client-cert.pem:ro",
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/worker/key.pem:/input/client-key.pem:ro",
		"buildkit_worker_credentials:/output",
	} {
		if !strings.Contains(workerInit, required) {
			return fmt.Errorf("worker BuildKit credential initializer is missing %q", required)
		}
	}
	if !strings.Contains(workerInit, "for stale in /output/* /output/.[!.]* /output/..?*; do [ ! -e ") || !strings.Contains(workerInit, "$$stale") {
		return errors.New("worker BuildKit credential initializer must clear stale volume contents before copying its identity")
	}
	if strings.Contains(workerInit, "/server/") || strings.Contains(workerInit, "/health/") || strings.Contains(workerInit, "ca-key.pem") {
		return errors.New("worker BuildKit credential initializer has access to a non-worker private key")
	}
	for _, required := range []string{
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/ca-cert.pem:/input/ca.pem:ro",
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/server/cert.pem:/input/server-cert.pem:ro",
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/server/key.pem:/input/server-key.pem:ro",
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/health/cert.pem:/input/health-client-cert.pem:ro",
		"${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls/health/key.pem:/input/health-client-key.pem:ro",
		"buildkit_server_credentials:/output",
	} {
		if !strings.Contains(serverInit, required) {
			return fmt.Errorf("BuildKit credential initializer is missing %q", required)
		}
	}
	if !strings.Contains(serverInit, "for stale in /output/* /output/.[!.]* /output/..?*; do [ ! -e ") || !strings.Contains(serverInit, "$$stale") {
		return errors.New("BuildKit credential initializer must clear stale volume contents before copying its identities")
	}
	if strings.Contains(serverInit, "/worker/") || strings.Contains(serverInit, "ca-key.pem") {
		return errors.New("BuildKit credential initializer has access to the worker private key or CA private key")
	}

	sourceInit := productionServiceBlock(text, "cloudflare-setup-state-init")
	for _, required := range []string{
		"network_mode: none", "restart: \"no\"", "read_only: true", "cap_drop: [ALL]", "user: \"0:0\"",
		"cap_add: [CHOWN, DAC_READ_SEARCH]",
		"entrypoint: [\"/usr/local/bin/stealth-cloudflare-state-init\"]",
		"${STEALTH_INSTALL_ROOT:-.}/state:/source:ro", "cloudflare_setup_state_input:/output:rw",
	} {
		if !strings.Contains(sourceInit, required) {
			return fmt.Errorf("Cloudflare source initializer is missing required setting %q", required)
		}
	}
	for _, forbidden := range []string{
		"./state:/state", "private", "buildkit-mtls", "ca-key.pem", "server/key.pem", "worker/key.pem", "health/key.pem",
		"FUNCTIONS_SECRET_KEY", "DATABASE_URL", "REDIS_URL", "CLOUDFLARE_API_TOKEN", "/var/run/docker.sock", "networks:", "environment:",
	} {
		if strings.Contains(sourceInit, forbidden) {
			return fmt.Errorf("Cloudflare source initializer contains forbidden setting %q", forbidden)
		}
	}
	if strings.Count(sourceInit, "cap_add:") != 1 || !strings.Contains(sourceInit, "cap_add: [CHOWN, DAC_READ_SEARCH]") {
		return errors.New("Cloudflare source initializer may add only CHOWN and DAC_READ_SEARCH")
	}

	cloudflareInit := productionServiceBlock(text, "cloudflare-state-init")
	for _, required := range []string{
		"network_mode: none", "read_only: true", "entrypoint: [\"/usr/local/bin/stealth-cloudflare-import-init\"]",
		"cloudflare_setup_state_input:/input:ro", "${STEALTH_INSTALL_ROOT:-.}/state/.cloudflare-import:/output:rw",
		"condition: service_completed_successfully", "FUNCTIONS_SECRET_KEY:",
	} {
		if !strings.Contains(cloudflareInit, required) {
			return fmt.Errorf("Cloudflare state initializer is missing required setting %q", required)
		}
	}
	for _, forbidden := range []string{
		"./state:/", "${STEALTH_INSTALL_ROOT:-.}/state:/", "private", "buildkit-mtls", "ca-key.pem", "server/key.pem", "worker/key.pem", "health/key.pem",
		"/source", "setup-state.enc:ro", "/var/run/docker.sock",
	} {
		if strings.Contains(cloudflareInit, forbidden) {
			return fmt.Errorf("Cloudflare state initializer contains forbidden setting %q", forbidden)
		}
	}
	for _, forbidden := range []string{
		"./private:", "${STEALTH_INSTALL_ROOT:-.}/private:", "./:/", ".:/", "${STEALTH_INSTALL_ROOT:-.}:/", "state/buildkit-mtls", "ca-key.pem",
	} {
		if strings.Contains(text, forbidden) {
			return fmt.Errorf("production Compose contains a broad or legacy private-state bind %q", forbidden)
		}
	}
	for _, name := range productionServiceNames(text) {
		block := productionServiceBlock(text, name)
		if name != "buildkit-worker-credentials-init" && name != "buildkit-server-credentials-init" &&
			(strings.Contains(block, "private/buildkit-mtls") || strings.Contains(block, "ca-key.pem") || strings.Contains(block, "/private:/")) {
			return fmt.Errorf("service %q can see private BuildKit PKI", name)
		}
	}
	for name, block := range map[string]string{"worker": workerInit, "BuildKit": serverInit} {
		for _, broadMount := range []string{"./private:", "${STEALTH_INSTALL_ROOT:-.}/private:", "./:/", ".:/", "${STEALTH_INSTALL_ROOT:-.}:/", "./private/buildkit-mtls:", "${STEALTH_INSTALL_ROOT:-.}/private/buildkit-mtls:"} {
			if strings.Contains(block, broadMount) {
				return fmt.Errorf("%s credential initializer has a broad BuildKit PKI mount %q", name, broadMount)
			}
		}
	}
	return nil
}

func productionServiceNames(contents string) []string {
	lines := strings.Split(contents, "\n")
	inServices := false
	var names []string
	for _, line := range lines {
		if line == "services:" {
			inServices = true
			continue
		}
		if !inServices {
			continue
		}
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "   ") && strings.HasSuffix(trimmed, ":") {
			names = append(names, strings.TrimSuffix(trimmed, ":"))
		}
	}
	return names
}

func productionServiceBlock(contents, wanted string) string {
	lines := strings.Split(contents, "\n")
	inServices := false
	active := false
	var block []string
	for _, line := range lines {
		if line == "services:" {
			inServices = true
			continue
		}
		if !inServices {
			continue
		}
		trimmed := strings.TrimSpace(line)
		isService := strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "   ") && strings.HasSuffix(trimmed, ":")
		if isService {
			name := strings.TrimSuffix(trimmed, ":")
			if active {
				return strings.Join(block, "\n")
			}
			if name == wanted {
				active = true
				block = append(block, line)
			}
			continue
		}
		if active {
			block = append(block, line)
		}
	}
	if active {
		return strings.Join(block, "\n")
	}
	return ""
}

func validateMainCollectorAsset(contents []byte) error {
	for _, marker := range [][]byte{[]byte("exporters:"), []byte("clickhouse:")} {
		if !bytes.Contains(contents, marker) {
			return fmt.Errorf("missing main Collector marker %q", marker)
		}
	}
	if bytes.Contains(contents, []byte("file_log/docker:")) {
		return errors.New("main Collector still contains the Docker file-log receiver")
	}
	return nil
}

func (m *managedAssetMigration) commit(plan Plan, originalEnv []byte, originalEnvExists bool, originalVersion []byte, originalVersionExists bool, originalVersionMode os.FileMode) error {
	if m == nil {
		return errors.New("managed asset migration is nil")
	}
	backupDir, err := os.MkdirTemp(m.layout.StateDir, ".stealth-managed-backup-")
	if err != nil {
		return fmt.Errorf("create managed asset recovery set: %w", err)
	}
	if err := os.Chmod(backupDir, 0o700); err != nil {
		_ = os.RemoveAll(backupDir)
		return fmt.Errorf("protect managed asset recovery set: %w", err)
	}
	m.backupDir = backupDir
	m.manifest = managedAssetRecoveryManifest{
		TransactionID:   filepath.Base(backupDir),
		TargetVersion:   strings.TrimSpace(plan.Version),
		OriginalVersion: strings.TrimSpace(plan.InstalledVersion),
		BackupDir:       filepath.Base(backupDir),
		StageDir:        filepath.Base(m.stageDir),
		Phase:           migrationPhasePrepared,
		Assets:          make([]managedAssetRecoveryEntry, 0, len(m.assets)),
		Config:          managedAssetRecoveryFile{Existed: originalEnvExists, Backup: "config.env", Mode: 0o600},
		Version:         managedAssetRecoveryFile{Existed: originalVersionExists, Backup: "VERSION", Mode: uint32(originalVersionMode)},
	}
	if m.manifest.OriginalVersion == "" && originalVersionExists {
		m.manifest.OriginalVersion = strings.TrimSpace(string(originalVersion))
	}
	if originalEnvExists {
		if err := WriteAtomic(filepath.Join(backupDir, m.manifest.Config.Backup), originalEnv, 0o600); err != nil {
			return m.failCommit(fmt.Errorf("back up config.env: %w", err))
		}
	}
	if originalVersionExists {
		mode := originalVersionMode
		if mode == 0 {
			mode = 0o644
			m.manifest.Version.Mode = uint32(mode)
		}
		if err := WriteAtomic(filepath.Join(backupDir, m.manifest.Version.Backup), originalVersion, mode); err != nil {
			return m.failCommit(fmt.Errorf("back up VERSION: %w", err))
		}
	}
	for index := range m.assets {
		asset := &m.assets[index]
		info, statErr := os.Lstat(asset.targetPath)
		if errors.Is(statErr, os.ErrNotExist) {
			m.manifest.Assets = append(m.manifest.Assets, managedAssetRecoveryEntry{RelativePath: asset.spec.Path})
			continue
		}
		if statErr != nil {
			return m.failCommit(fmt.Errorf("inspect managed asset %q: %w", asset.spec.Path, statErr))
		}
		if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return m.failCommit(fmt.Errorf("managed asset %q is not a regular file", asset.spec.Path))
		}
		asset.existed = true
		asset.backupPath = filepath.Join(backupDir, filepath.FromSlash(asset.spec.Path))
		if err := os.MkdirAll(filepath.Dir(asset.backupPath), 0o700); err != nil {
			return m.failCommit(fmt.Errorf("prepare recovery path for %q: %w", asset.spec.Path, err))
		}
		m.manifest.Assets = append(m.manifest.Assets, managedAssetRecoveryEntry{RelativePath: asset.spec.Path, Existed: true})
	}
	if err := m.writeJournal(); err != nil {
		return m.failCommit(err)
	}
	m.journalWritten = true
	if err := m.notify(MigrationEvent{Phase: migrationPhasePrepared}); err != nil {
		return m.failCommit(err)
	}
	backupIndex := 0
	for index := range m.assets {
		asset := &m.assets[index]
		if !asset.existed {
			continue
		}
		if err := renameAndSync(asset.targetPath, asset.backupPath); err != nil {
			return m.failCommit(fmt.Errorf("save previous managed asset %q: %w", asset.spec.Path, err))
		}
		asset.backedUp = true
		backupIndex++
		if err := m.notify(MigrationEvent{Phase: migrationEventBackupRenamed, Asset: asset.spec.Path, Index: backupIndex, Total: len(m.assets)}); err != nil {
			return m.failCommit(err)
		}
	}
	if err := m.transition(migrationPhaseBackedUp); err != nil {
		return m.failCommit(err)
	}
	for index := range m.assets {
		asset := &m.assets[index]
		if err := os.MkdirAll(filepath.Dir(asset.targetPath), 0o700); err != nil {
			return m.failCommit(fmt.Errorf("create managed asset directory for %q: %w", asset.spec.Path, err))
		}
		if err := renameAndSync(asset.stagePath, asset.targetPath); err != nil {
			return m.failCommit(fmt.Errorf("activate managed asset %q: %w", asset.spec.Path, err))
		}
		asset.installed = true
		if err := m.notify(MigrationEvent{Phase: migrationEventAssetActivated, Asset: asset.spec.Path, Index: index + 1, Total: len(m.assets)}); err != nil {
			return m.failCommit(err)
		}
	}
	if err := m.transition(migrationPhaseAssetsActivated); err != nil {
		return m.failCommit(err)
	}
	return nil
}

func (m *managedAssetMigration) transition(phase migrationPhase) error {
	if m == nil || !m.journalWritten {
		return errors.New("managed asset recovery journal is not active")
	}
	m.manifest.Phase = phase
	if err := m.writeJournal(); err != nil {
		return err
	}
	return m.notify(MigrationEvent{Phase: phase})
}

func (m *managedAssetMigration) notify(event MigrationEvent) error {
	if m != nil && m.hook != nil {
		if err := m.hook(event); err != nil {
			return err
		}
	}
	return nil
}

func (m *managedAssetMigration) writeJournal() error {
	contents, err := json.Marshal(m.manifest)
	if err != nil {
		return fmt.Errorf("encode managed asset recovery journal: %w", err)
	}
	if err := WriteAtomic(filepath.Join(m.layout.StateDir, managedAssetPendingFile), contents, 0o600); err != nil {
		return fmt.Errorf("write managed asset recovery journal: %w", err)
	}
	return nil
}

func (m *managedAssetMigration) failCommit(cause error) error {
	if errors.Is(cause, errMigrationProcessInterrupted) {
		return cause
	}
	return errors.Join(cause, m.rollback())
}

func (m *managedAssetMigration) rollback() error {
	if m == nil {
		return nil
	}
	if !m.journalWritten {
		var cleanupErr error
		if m.backupDir != "" {
			cleanupErr = errors.Join(cleanupErr, removeAllAndSync(m.backupDir))
		}
		if m.stageDir != "" {
			cleanupErr = errors.Join(cleanupErr, removeAllAndSync(m.stageDir))
		}
		return cleanupErr
	}
	return recoverInterruptedManagedAssetMigration(m.layout, m.allowedPaths)
}

func (m *managedAssetMigration) finalize() error {
	if m == nil {
		return nil
	}
	if m.manifest.Phase != migrationPhaseComposeValidated {
		return errors.New("managed asset migration has not passed Compose validation")
	}
	// Do not discard the previous recovery set until the new complete backup
	// exists and the new platform has passed Compose validation. If this process
	// dies during publication, recovery sees COMPOSE_VALIDATED and completes
	// forward without exposing a mixed release.
	if err := publishManagedAssetRecoverySet(m.layout, m.manifest); err != nil {
		return err
	}
	m.manifest.Phase = migrationPhaseFinalized
	if err := m.writeJournal(); err != nil {
		return err
	}
	return removeAndSync(filepath.Join(m.layout.StateDir, managedAssetPendingFile))
}

// Wait checks the host-visible service endpoints for CLI plans and the
// Compose-network endpoints for browser handoff plans. A public URL is only
// probed when the plan explicitly requests the final ingress check.
func (e *Engine) Wait(ctx context.Context, plan Plan) error {
	values, err := ReadEnvFile(plan.Layout.EnvFile)
	if err != nil {
		return fmt.Errorf("read installation configuration: %w", err)
	}
	apiURL := strings.TrimRight(plan.InternalAPIURL, "/")
	consoleURL := strings.TrimRight(plan.InternalConsoleURL, "/")
	proxyURL := strings.TrimRight(plan.InternalProxyURL, "/")
	if apiURL == "" {
		apiURL = "http://127.0.0.1:" + PortOrDefault(values["API_HOST_PORT"], "18080")
	}
	if consoleURL == "" {
		consoleURL = "http://127.0.0.1:" + PortOrDefault(values["CONSOLE_HOST_PORT"], "13000")
	}
	if proxyURL == "" {
		proxyURL = "http://127.0.0.1:" + PortOrDefault(values["PROXY_HTTP_PORT"], "8080")
	}
	endpoints := []string{apiURL + "/healthz", apiURL + "/readyz", apiURL + "/version", consoleURL + "/", proxyURL + "/"}
	if plan.VerifyPublicURL && strings.TrimRight(plan.PublicURL, "/") != "" {
		endpoints = append(endpoints, strings.TrimRight(plan.PublicURL, "/")+"/")
	}
	maxWait := time.Duration(e.pollAttempts)*e.pollInterval + 30*time.Second
	waitContext, cancel := context.WithTimeout(ctx, maxWait)
	defer cancel()
	for attempt := 0; attempt < e.pollAttempts; attempt++ {
		if err := waitContext.Err(); err != nil {
			return err
		}
		allReady := true
		for _, endpoint := range endpoints {
			status, requestErr := e.httpStatus(waitContext, endpoint)
			if requestErr != nil || status < 200 || status >= 300 {
				allReady = false
				break
			}
		}
		if allReady {
			return nil
		}
		if attempt+1 < e.pollAttempts {
			if err := waitInterval(waitContext, e.pollInterval); err != nil {
				return err
			}
		}
	}
	return fmt.Errorf("services did not become ready after %d checks", e.pollAttempts)
}

func (e *Engine) runCompose(ctx context.Context, plan Plan, args ...string) error {
	composeFile := plan.Layout.ComposeFile
	if plan.Setup && plan.Layout.SetupComposeFile != "" {
		composeFile = plan.Layout.SetupComposeFile
	}
	return e.runComposeFile(ctx, plan, composeFile, "", args...)
}

func (e *Engine) runTraefikStateInit(ctx context.Context, plan Plan, composeFile, projectDirectory string) error {
	args := []string{
		"run", "--rm", "--no-deps",
		"-e", fmt.Sprintf("STEALTH_TRAEFIK_HOST_UID=%d", os.Geteuid()),
		"traefik-state-init",
	}
	return e.runComposeFile(ctx, plan, composeFile, projectDirectory, args...)
}

func (e *Engine) runComposeFile(ctx context.Context, plan Plan, composeFile, projectDirectory string, args ...string) error {
	composeArgs := []string{"compose"}
	if plan.Cloudflare {
		composeArgs = append(composeArgs, "--profile", "cloudflare")
	}
	if projectDirectory != "" {
		composeArgs = append(composeArgs, "--project-directory", projectDirectory)
	}
	if strings.TrimSpace(composeFile) == "" {
		return errors.New("Compose file is required")
	}
	composeArgs = append(composeArgs, "--env-file", plan.Layout.EnvFile, "-f", composeFile)
	composeArgs = append(composeArgs, args...)
	if err := e.runner.Run(ctx, plan.Layout.Root, e.output, e.output, "docker", composeArgs...); err != nil {
		return fmt.Errorf("docker compose %v failed: %w", args, err)
	}
	return nil
}

func (e *Engine) fetchAsset(ctx context.Context, assetURL string) ([]byte, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, assetURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create asset request: %w", err)
	}
	response, err := e.httpClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("download asset: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download asset returned HTTP %d", response.StatusCode)
	}
	contents, err := io.ReadAll(io.LimitReader(response.Body, maxAssetSize+1))
	if err != nil {
		return nil, fmt.Errorf("read downloaded asset: %w", err)
	}
	if len(contents) > maxAssetSize {
		return nil, errors.New("downloaded asset is unexpectedly large")
	}
	return contents, nil
}

// RunCommand exposes the same process boundary used by installation steps for
// narrowly scoped lifecycle operations such as removing the exact temporary
// onboarding container. Callers must validate any resource name before
// passing it here; this method is not a general shell interface.
func (e *Engine) RunCommand(ctx context.Context, dir, name string, args ...string) error {
	if e == nil || e.runner == nil {
		return errors.New("install engine is not configured")
	}
	return e.runner.Run(ctx, dir, io.Discard, io.Discard, name, args...)
}

func (e *Engine) httpStatus(ctx context.Context, endpoint string) (int, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return 0, err
	}
	response, err := e.httpClient.Do(request)
	if err != nil {
		return 0, err
	}
	defer response.Body.Close()
	_, _ = io.Copy(io.Discard, io.LimitReader(response.Body, 4096))
	return response.StatusCode, nil
}

func waitInterval(ctx context.Context, interval time.Duration) error {
	if interval <= 0 {
		return nil
	}
	timer := time.NewTimer(interval)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func acquireLock(stateDir string) (*os.File, error) {
	if strings.TrimSpace(stateDir) == "" {
		return nil, errors.New("installation state directory is required")
	}
	return AcquireProcessLock(stateDir, lockFileName, "installation")
}

// AcquireProcessLock takes a non-blocking exclusive advisory lock on
// stateDir/name and returns the open lock file. Closing the file releases the
// lock, so a crashed process cannot leave a stale lock behind. Callers use this
// to guarantee that only one process owns a long-running operation such as a
// host-side setup orchestration or a production install.
func AcquireProcessLock(stateDir, name, description string) (*os.File, error) {
	if strings.TrimSpace(stateDir) == "" {
		return nil, errors.New("lock directory is required")
	}
	name = strings.TrimSpace(name)
	if name == "" || name == "." || name == ".." || filepath.Base(name) != name || strings.ContainsAny(name, `/\`) {
		return nil, errors.New("lock name is invalid")
	}
	if err := os.MkdirAll(stateDir, 0o700); err != nil {
		return nil, fmt.Errorf("create %s lock directory: %w", description, err)
	}
	lockPath := filepath.Join(stateDir, name)
	file, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("open %s lock: %w", description, err)
	}
	if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		_ = file.Close()
		if errors.Is(err, syscall.EWOULDBLOCK) {
			if description == "installation" {
				return nil, ErrOperationInProgress
			}
			return nil, fmt.Errorf("another %s operation is already running", description)
		}
		return nil, fmt.Errorf("lock %s: %w", description, err)
	}
	return file, nil
}

func safeError(err error) string {
	if err == nil {
		return ""
	}
	// Compose errors are allowed to include service names and status codes, but
	// never copy a command's output into a browser event. The command runner is
	// configured with a discard writer by the HTTP composition root.
	message := strings.TrimSpace(err.Error())
	if len(message) > 240 {
		message = message[:240]
	}
	return message
}

// The small wrappers below are intentionally exported so the CLI can delete
// its duplicate file/configuration implementation while preserving its
// existing tests and operator behavior.
func FileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Mode()&os.ModeSymlink == 0
}

func FileIsPrivate(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Mode().Perm()&0o077 == 0
}

func WritePrivateFile(path, contents string) error {
	return WriteAtomic(path, []byte(contents), 0o600)
}

func WriteAtomic(path string, contents []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".stealth-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return err
	}
	if err := os.Chmod(path, mode); err != nil {
		return err
	}
	if err := syncFile(path); err != nil {
		return err
	}
	return syncDirectory(filepath.Dir(path))
}

func syncFile(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()
	return file.Sync()
}

func ReadEnvFile(path string) (map[string]string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return ParseEnvContents(string(contents))
}

func ParseEnvContents(contents string) (map[string]string, error) {
	values := make(map[string]string)
	for lineNumber, rawLine := range strings.Split(contents, "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return nil, fmt.Errorf("invalid config.env line %d", lineNumber+1)
		}
		values[key] = strings.Trim(value, " \t")
	}
	return values, nil
}

func ValidEnvKey(value string) bool {
	if value == "" {
		return false
	}
	for index, character := range value {
		if (character < 'A' || character > 'Z') && (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '_' {
			return false
		}
		if index == 0 && character >= '0' && character <= '9' {
			return false
		}
	}
	return true
}

func FormatEnvFile(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by Stealth. Keep this file private.\n")
	for _, key := range keys {
		builder.WriteString(key)
		builder.WriteByte('=')
		builder.WriteString(values[key])
		builder.WriteByte('\n')
	}
	return builder.String()
}

func MergeEnv(base map[string]string, updates map[string]string) (string, error) {
	values := make(map[string]string, len(base)+len(updates))
	for key, value := range base {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	for key, value := range updates {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	return FormatEnvFile(values), nil
}

func PortOrDefault(raw, fallback string) string {
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || value < 1 || value > 65535 {
		return fallback
	}
	return strconv.Itoa(value)
}
