// Package installengine owns the idempotent installation primitives used by
// the host CLI. UI and setup API layers select or project state; this package
// owns files, Compose, and health checks without exposing a shell boundary to
// the browser.
package installengine

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

const (
	defaultAssetBase = "https://raw.githubusercontent.com/Stealth-deplover/stealth"
	maxAssetSize     = 2 << 20
	lockFileName     = "install.lock"
)

// ErrOperationInProgress lets a recovering worker distinguish lock ownership
// from an installation failure. A worker that loses the race leaves the
// durable run in installing so the lock owner can continue publishing state;
// a later process can resume it after a crash releases the OS lock.
var ErrOperationInProgress = errors.New("another installation operation is already running")

// CommandRunner is the only process boundary the host engine needs. The setup
// API does not construct an engine or receive a command runner.
type CommandRunner interface {
	Run(context.Context, string, io.Writer, io.Writer, string, ...string) error
	Output(context.Context, string, string, ...string) ([]byte, error)
}

// OSCommandRunner executes the Docker Compose commands selected by a plan.
// It is intentionally small so tests can assert the exact command surface.
type OSCommandRunner struct{}

func (OSCommandRunner) Run(ctx context.Context, dir string, stdout, stderr io.Writer, name string, args ...string) error {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	command.Stdout = stdout
	command.Stderr = stderr
	return command.Run()
}

func (OSCommandRunner) Output(ctx context.Context, dir, name string, args ...string) ([]byte, error) {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	return command.Output()
}

// Layout is the on-host installation boundary. The host CLI writes durable
// production files and runs Compose from this root; the setup API only shares
// the separate encrypted state directory.
type Layout struct {
	Root             string
	EnvFile          string
	ComposeFile      string
	SetupComposeFile string
	TelemetryDir     string
	ProxyFile        string
	VersionFile      string
	StateDir         string
}

func NewLayout(root string) (Layout, error) {
	root = strings.TrimSpace(root)
	if root == "" {
		return Layout{}, errors.New("installation root is required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve installation root: %w", err)
	}
	clean := filepath.Clean(abs)
	if clean == string(filepath.Separator) {
		return Layout{}, errors.New("refusing filesystem root as installation root")
	}
	return Layout{
		Root:             clean,
		EnvFile:          filepath.Join(clean, "config.env"),
		ComposeFile:      filepath.Join(clean, "compose.production.yaml"),
		SetupComposeFile: filepath.Join(clean, "compose.setup.yaml"),
		TelemetryDir:     filepath.Join(clean, "telemetry"),
		ProxyFile:        filepath.Join(clean, "console", "deploy", "nginx.conf"),
		VersionFile:      filepath.Join(clean, "VERSION"),
		StateDir:         filepath.Join(clean, "state"),
	}, nil
}

// Plan contains only installation decisions. Secrets are generated by the
// engine for a fresh plan or are supplied as already-rendered ConfigContents
// for a browser-confirmed plan.
type Plan struct {
	Layout  Layout
	Version string
	// InstalledVersion is the release currently recorded by an existing
	// installation. Version is the target release for this operation. Keeping
	// both values lets managed configuration advance canonical image references
	// without overwriting operator-selected image overrides.
	InstalledVersion   string
	PublicURL          string
	GitHubAppClientID  string
	DockerGID          uint32
	Existing           bool
	Setup              bool
	ExternalDatabase   bool
	ExternalRedis      bool
	Cloudflare         bool
	VerifyPublicURL    bool
	ConfigContents     string
	InternalAPIURL     string
	InternalConsoleURL string
	InternalProxyURL   string
}

type Step int

const (
	StepConfiguration Step = iota
	StepPull
	StepDependencies
	StepMigration
	StepServices
	StepVerify
)

var StepNames = []string{
	"Configuration and secrets",
	"Release images",
	"PostgreSQL and Redis",
	"Database migrations",
	"API, Worker, Console, and Proxy",
	"Health and readiness verification",
}

type Event struct {
	Step    string    `json:"step"`
	Status  string    `json:"status"`
	Message string    `json:"message,omitempty"`
	Error   string    `json:"error,omitempty"`
	At      time.Time `json:"at"`
}

type Options struct {
	Runner       CommandRunner
	HTTPClient   *http.Client
	AssetBaseURL string
	Output       io.Writer
	PollAttempts int
	PollInterval time.Duration
}

type Engine struct {
	runner       CommandRunner
	httpClient   *http.Client
	assetBaseURL string
	output       io.Writer
	pollAttempts int
	pollInterval time.Duration
}

func New(options Options) *Engine {
	runner := options.Runner
	if runner == nil {
		runner = OSCommandRunner{}
	}
	httpClient := options.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{Timeout: 20 * time.Second}
	}
	assetBaseURL := strings.TrimRight(strings.TrimSpace(options.AssetBaseURL), "/")
	if assetBaseURL == "" {
		assetBaseURL = defaultAssetBase
	}
	attempts := options.PollAttempts
	if attempts < 1 {
		attempts = 60
	}
	interval := options.PollInterval
	if interval <= 0 {
		interval = 2 * time.Second
	}
	output := options.Output
	if output == nil {
		output = io.Discard
	}
	return &Engine{runner: runner, httpClient: httpClient, assetBaseURL: assetBaseURL, output: output, pollAttempts: attempts, pollInterval: interval}
}

// Install executes every step while holding an OS-level lock. The lock is
// released on process exit, so a restarted host CLI can safely resume a
// partial installation without manual lock-file cleanup.
func (e *Engine) Install(ctx context.Context, plan Plan, emit func(Event)) error {
	if e == nil {
		return errors.New("install engine is nil")
	}
	lock, err := acquireLock(plan.Layout.StateDir)
	if err != nil {
		return err
	}
	defer lock.Close()
	return e.InstallLocked(ctx, plan, emit)
}

// InstallLocked executes every step after the caller has acquired the
// installation lock. It exists for the host orchestrator, which must hold the
// same lock while it claims the durable InstallRunID and performs handoff
// cleanup. Callers must not invoke this method without owning the lock for
// plan.Layout.StateDir.
func (e *Engine) InstallLocked(ctx context.Context, plan Plan, emit func(Event)) error {
	if e == nil {
		return errors.New("install engine is nil")
	}
	for step := StepConfiguration; step <= StepVerify; step++ {
		event := Event{Step: StepNames[step], Status: "started", At: time.Now().UTC()}
		if emit != nil {
			emit(event)
		}
		if err := e.RunStep(ctx, plan, step); err != nil {
			event.Status = "failed"
			event.Error = safeError(err)
			event.At = time.Now().UTC()
			if emit != nil {
				emit(event)
			}
			return err
		}
		event.Status = "succeeded"
		event.Message = "complete"
		event.At = time.Now().UTC()
		if emit != nil {
			emit(event)
		}
	}
	return nil
}

func (e *Engine) RunStep(ctx context.Context, plan Plan, step Step) error {
	switch step {
	case StepConfiguration:
		prepared, err := e.prepareInstallation(ctx, plan)
		if err != nil {
			return err
		}
		if err := prepared.commit(plan); err != nil {
			return err
		}
		if err := e.runCompose(ctx, plan, "config", "--quiet"); err != nil {
			rollbackErr := prepared.rollback()
			return errors.Join(err, rollbackErr)
		}
		prepared.finalize()
		return nil
	case StepPull:
		return e.runCompose(ctx, plan, "pull")
	case StepDependencies:
		if !plan.Setup {
			// StepServices may use --no-deps for external PostgreSQL/Redis.
			// Run both ownership init services explicitly so that path never
			// bypasses either non-root Collector's persistent file_storage
			// preparation.
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "otelcol-state-init"); err != nil {
				return err
			}
			if err := e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "telemetry-docker-logs-state-init"); err != nil {
				return err
			}
		}
		services := make([]string, 0, 3)
		if !plan.ExternalDatabase {
			services = append(services, "postgres")
		}
		if !plan.ExternalRedis {
			services = append(services, "redis")
		}
		if !plan.Setup {
			services = append(services, "clickhouse")
		}
		if len(services) == 0 {
			return nil
		}
		return e.runCompose(ctx, plan, append([]string{"up", "-d"}, services...)...)
	case StepMigration:
		if plan.ExternalDatabase {
			return e.runCompose(ctx, plan, "run", "--rm", "--no-deps", "migrate")
		}
		return e.runCompose(ctx, plan, "up", "migrate")
	case StepServices:
		services := []string{"api", "worker", "console", "proxy"}
		if plan.Setup {
			services = []string{"setup", "setup-console", "setup-proxy"}
		} else {
			services = append(services, "otel-collector", "telemetry-host", "telemetry-docker-logs", "telemetry-docker-proxy", "telemetry-docker")
		}
		if plan.Cloudflare {
			services = append(services, "cloudflared")
		}
		args := []string{"up", "-d"}
		if plan.ExternalDatabase || plan.ExternalRedis {
			args = append(args, "--no-deps")
		}
		args = append(args, services...)
		return e.runCompose(ctx, plan, args...)
	case StepVerify:
		return e.Wait(ctx, plan)
	default:
		return fmt.Errorf("unknown install step %d", step)
	}
}

type managedAssetSpec struct {
	relativePath string
	remotePath   string
	marker       []byte
	validate     func([]byte) error
}

type stagedManagedAsset struct {
	spec       managedAssetSpec
	targetPath string
	stagePath  string
	backupPath string
	existed    bool
	backedUp   bool
	installed  bool
}

const managedAssetPendingFile = "managed-assets.pending"

type managedAssetRecoveryManifest struct {
	BackupDir string                      `json:"backup_dir"`
	Assets    []managedAssetRecoveryEntry `json:"assets"`
}

type managedAssetRecoveryEntry struct {
	RelativePath string `json:"relative_path"`
	Existed      bool   `json:"existed"`
}

// managedAssetMigration stages the complete release-managed runtime set before
// changing the installation. Existing managed files are moved into one
// bounded recovery set, never copied with secrets, and restored if a later
// commit step or Compose validation fails.
type managedAssetMigration struct {
	layout         Layout
	stageDir       string
	backupDir      string
	previousBackup string
	assets         []stagedManagedAsset
	committed      bool
}

type preparedInstallation struct {
	layout             Layout
	assets             *managedAssetMigration
	originalEnv        []byte
	originalEnvExists  bool
	newEnv             []byte
	originalVersion    []byte
	originalVersionSet bool
}

func (e *Engine) Prepare(ctx context.Context, plan Plan) error {
	prepared, err := e.prepareInstallation(ctx, plan)
	if err != nil {
		return err
	}
	if err := prepared.commit(plan); err != nil {
		return err
	}
	prepared.finalize()
	return nil
}

// prepareInstallation downloads and validates the full managed asset set but
// does not publish it until commit. RunStep uses the returned transaction to
// roll the files back when docker compose config validation fails.
func (e *Engine) prepareInstallation(ctx context.Context, plan Plan) (*preparedInstallation, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if plan.Layout.Root == "" || plan.Layout.EnvFile == "" || plan.Layout.ComposeFile == "" {
		return nil, errors.New("installation layout is incomplete")
	}
	if err := ValidateReleaseVersion(strings.TrimSpace(plan.Version)); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(plan.Layout.Root, 0o700); err != nil {
		return nil, fmt.Errorf("create installation directory: %w", err)
	}
	if err := os.Chmod(plan.Layout.Root, 0o700); err != nil {
		return nil, fmt.Errorf("protect installation directory: %w", err)
	}
	// Setup state is shared by the host CLI and the root setup container. The
	// setgid directory preserves the host operator's group on files atomically
	// replaced by the container, while the state payload remains group-private.
	stateDirectoryMode := os.FileMode(0o770) | os.ModeSetgid
	if err := os.MkdirAll(plan.Layout.StateDir, stateDirectoryMode); err != nil {
		return nil, fmt.Errorf("create state directory: %w", err)
	}
	if err := os.Chmod(plan.Layout.StateDir, stateDirectoryMode); err != nil {
		return nil, fmt.Errorf("protect state directory: %w", err)
	}
	prepared := &preparedInstallation{
		layout: plan.Layout,
	}
	if contents, err := os.ReadFile(plan.Layout.VersionFile); err == nil {
		prepared.originalVersion = contents
		prepared.originalVersionSet = true
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("read existing version: %w", err)
	}
	if plan.Existing {
		if !FileIsPrivate(plan.Layout.EnvFile) {
			return nil, errors.New("existing configuration permissions are too broad; expected mode 0600")
		}
		contents, err := os.ReadFile(plan.Layout.EnvFile)
		if err != nil {
			return nil, fmt.Errorf("read existing configuration: %w", err)
		}
		values, err := ReadEnvFile(plan.Layout.EnvFile)
		if err != nil {
			return nil, fmt.Errorf("parse existing configuration: %w", err)
		}
		installedVersion := strings.TrimSpace(plan.InstalledVersion)
		if installedVersion == "" && prepared.originalVersionSet {
			installedVersion = strings.TrimSpace(string(prepared.originalVersion))
			if err := ValidateReleaseVersion(installedVersion); err != nil {
				return nil, fmt.Errorf("existing VERSION is invalid: %w", err)
			}
		}
		if installedVersion == "" {
			installedVersion = strings.TrimSpace(plan.Version)
		}
		migrated, err := MigrateReleaseConfig(values, plan.Version, installedVersion)
		if err != nil {
			return nil, fmt.Errorf("prepare existing configuration migration: %w", err)
		}
		prepared.originalEnv = contents
		prepared.originalEnvExists = true
		prepared.newEnv = []byte(migrated)
	} else {
		contents := plan.ConfigContents
		if strings.TrimSpace(contents) == "" {
			var err error
			contents, err = GenerateConfig(ConfigOptions{Version: plan.Version, PublicURL: plan.PublicURL, GitHubAppClientID: plan.GitHubAppClientID, DockerGID: plan.DockerGID, Setup: plan.Setup, InstallRoot: plan.Layout.Root})
			if err != nil {
				return nil, fmt.Errorf("generate configuration: %w", err)
			}
		}
		prepared.newEnv = []byte(contents)
	}
	assets, err := e.stageManagedAssets(ctx, plan)
	if err != nil {
		return nil, err
	}
	prepared.assets = assets
	return prepared, nil
}

func (p *preparedInstallation) commit(plan Plan) error {
	if p == nil || p.assets == nil {
		return errors.New("prepared installation is incomplete")
	}
	if err := p.assets.commit(); err != nil {
		return err
	}
	if err := WritePrivateFile(p.layout.EnvFile, string(p.newEnv)); err != nil {
		rollbackErr := p.rollback()
		return errors.Join(fmt.Errorf("write configuration: %w", err), rollbackErr)
	}
	if err := WriteAtomic(p.layout.VersionFile, []byte(strings.TrimSpace(plan.Version)+"\n"), 0o644); err != nil {
		rollbackErr := p.rollback()
		return errors.Join(fmt.Errorf("write version file: %w", err), rollbackErr)
	}
	return nil
}

func (p *preparedInstallation) rollback() error {
	if p == nil {
		return nil
	}
	var rollbackErr error
	if p.assets != nil {
		rollbackErr = errors.Join(rollbackErr, p.assets.rollback())
	}
	if p.originalEnvExists {
		rollbackErr = errors.Join(rollbackErr, WritePrivateFile(p.layout.EnvFile, string(p.originalEnv)))
	} else if err := os.Remove(p.layout.EnvFile); err != nil && !errors.Is(err, os.ErrNotExist) {
		rollbackErr = errors.Join(rollbackErr, err)
	}
	if p.originalVersionSet {
		rollbackErr = errors.Join(rollbackErr, WriteAtomic(p.layout.VersionFile, p.originalVersion, 0o644))
	} else if err := os.Remove(p.layout.VersionFile); err != nil && !errors.Is(err, os.ErrNotExist) {
		rollbackErr = errors.Join(rollbackErr, err)
	}
	return rollbackErr
}

func (p *preparedInstallation) finalize() {
	if p != nil && p.assets != nil {
		p.assets.finalize()
	}
}

func managedAssetSpecs(plan Plan) []managedAssetSpec {
	assets := []managedAssetSpec{
		{relativePath: "compose.production.yaml", remotePath: "compose.production.yaml", marker: []byte("services:"), validate: validateProductionComposeAsset},
		{relativePath: "console/deploy/nginx.conf", remotePath: "console/deploy/nginx.conf", marker: []byte("server {")},
		{relativePath: "telemetry/otel-collector.yaml", remotePath: "telemetry/otel-collector.yaml", marker: []byte("receivers:"), validate: validateMainCollectorAsset},
		{relativePath: "telemetry/host-metrics.yaml", remotePath: "telemetry/host-metrics.yaml", marker: []byte("hostmetrics:")},
		{relativePath: "telemetry/docker-logs.yaml", remotePath: "telemetry/docker-logs.yaml", marker: []byte("file_log/docker:")},
		{relativePath: "telemetry/docker-stats.yaml", remotePath: "telemetry/docker-stats.yaml", marker: []byte("docker_stats:")},
	}
	if plan.Layout.SetupComposeFile != "" && (plan.Setup || (plan.Existing && FileExists(plan.Layout.SetupComposeFile))) {
		assets = append(assets, managedAssetSpec{relativePath: "compose.setup.yaml", remotePath: "compose.setup.yaml", marker: []byte("services:")})
	}
	return assets
}

func (e *Engine) stageManagedAssets(ctx context.Context, plan Plan) (*managedAssetMigration, error) {
	if err := recoverInterruptedManagedAssetMigration(plan.Layout); err != nil {
		return nil, fmt.Errorf("recover interrupted managed asset migration: %w", err)
	}
	stageDir, err := os.MkdirTemp(plan.Layout.StateDir, ".stealth-managed-assets-")
	if err != nil {
		return nil, fmt.Errorf("create managed asset staging directory: %w", err)
	}
	migration := &managedAssetMigration{
		layout:         plan.Layout,
		stageDir:       stageDir,
		previousBackup: filepath.Join(plan.Layout.StateDir, "managed-assets.previous"),
	}
	cleanup := func() {
		_ = os.RemoveAll(stageDir)
	}
	for _, spec := range managedAssetSpecs(plan) {
		contents, err := e.fetchAsset(ctx, e.assetBaseURL+"/"+strings.TrimSpace(plan.Version)+"/"+spec.remotePath)
		if err != nil {
			cleanup()
			return nil, fmt.Errorf("download managed asset %q: %w", spec.remotePath, err)
		}
		if !bytes.Contains(contents, spec.marker) {
			cleanup()
			return nil, fmt.Errorf("downloaded asset %q is invalid", spec.remotePath)
		}
		if spec.validate != nil {
			if err := spec.validate(contents); err != nil {
				cleanup()
				return nil, fmt.Errorf("downloaded asset %q failed validation: %w", spec.remotePath, err)
			}
		}
		stagePath := filepath.Join(stageDir, filepath.FromSlash(spec.relativePath))
		if err := WriteAtomic(stagePath, contents, 0o644); err != nil {
			cleanup()
			return nil, fmt.Errorf("stage managed asset %q: %w", spec.remotePath, err)
		}
		migration.assets = append(migration.assets, stagedManagedAsset{
			spec:       spec,
			targetPath: filepath.Join(plan.Layout.Root, filepath.FromSlash(spec.relativePath)),
			stagePath:  stagePath,
		})
	}
	return migration, nil
}

func recoverInterruptedManagedAssetMigration(layout Layout) error {
	pendingPath := filepath.Join(layout.StateDir, managedAssetPendingFile)
	if info, err := os.Lstat(pendingPath); err == nil {
		if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("managed asset recovery journal is not a regular file")
		}
		contents, err := os.ReadFile(pendingPath)
		if err != nil {
			return fmt.Errorf("read managed asset recovery journal: %w", err)
		}
		var manifest managedAssetRecoveryManifest
		if err := json.Unmarshal(contents, &manifest); err != nil {
			return fmt.Errorf("parse managed asset recovery journal: %w", err)
		}
		if filepath.Base(manifest.BackupDir) != manifest.BackupDir || !strings.HasPrefix(manifest.BackupDir, ".stealth-managed-backup-") {
			return errors.New("managed asset recovery journal contains an invalid backup path")
		}
		backupPath := filepath.Join(layout.StateDir, manifest.BackupDir)
		if info, err := os.Lstat(backupPath); err != nil {
			if !errors.Is(err, os.ErrNotExist) {
				return fmt.Errorf("inspect interrupted managed asset recovery set: %w", err)
			}
			backupPath = filepath.Join(layout.StateDir, "managed-assets.previous")
			info, err := os.Lstat(backupPath)
			if err != nil {
				return fmt.Errorf("inspect published managed asset recovery set: %w", err)
			}
			if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
				return errors.New("published managed asset recovery set is not a directory")
			}
		} else if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("interrupted managed asset recovery set is not a directory")
		}
		seen := make(map[string]struct{}, len(manifest.Assets))
		for _, entry := range manifest.Assets {
			if !isManagedAssetPath(entry.RelativePath) {
				return fmt.Errorf("managed asset recovery journal contains unknown path %q", entry.RelativePath)
			}
			if _, ok := seen[entry.RelativePath]; ok {
				return fmt.Errorf("managed asset recovery journal contains duplicate path %q", entry.RelativePath)
			}
			seen[entry.RelativePath] = struct{}{}
			targetPath := filepath.Join(layout.Root, filepath.FromSlash(entry.RelativePath))
			if entry.Existed {
				sourcePath := filepath.Join(backupPath, filepath.FromSlash(entry.RelativePath))
				if _, err := os.Lstat(sourcePath); errors.Is(err, os.ErrNotExist) {
					// The journal is written before the first rename. If a
					// process stopped in that small window, the original target
					// is still authoritative and needs no restoration.
					targetInfo, targetErr := os.Lstat(targetPath)
					if targetErr != nil {
						return fmt.Errorf("recover previous managed asset %q: %w", entry.RelativePath, targetErr)
					}
					if !targetInfo.Mode().IsRegular() || targetInfo.Mode()&os.ModeSymlink != 0 {
						return fmt.Errorf("recover previous managed asset %q: target is not a regular file", entry.RelativePath)
					}
					continue
				} else if err != nil {
					return fmt.Errorf("recover previous managed asset %q: %w", entry.RelativePath, err)
				}
				if err := removeManagedAssetTarget(targetPath); err != nil {
					return fmt.Errorf("clear interrupted managed asset %q: %w", entry.RelativePath, err)
				}
				if err := os.MkdirAll(filepath.Dir(targetPath), 0o700); err != nil {
					return fmt.Errorf("prepare managed asset recovery path %q: %w", entry.RelativePath, err)
				}
				if err := os.Rename(sourcePath, targetPath); err != nil {
					return fmt.Errorf("restore managed asset %q: %w", entry.RelativePath, err)
				}
				continue
			}
			if err := removeManagedAssetTarget(targetPath); err != nil {
				return fmt.Errorf("remove partially activated managed asset %q: %w", entry.RelativePath, err)
			}
		}
		if err := os.RemoveAll(backupPath); err != nil {
			return fmt.Errorf("remove recovered managed asset set: %w", err)
		}
		if err := os.Remove(pendingPath); err != nil {
			return fmt.Errorf("remove managed asset recovery journal: %w", err)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect managed asset recovery journal: %w", err)
	}

	entries, err := os.ReadDir(layout.StateDir)
	if err != nil {
		return fmt.Errorf("inspect managed asset staging directory: %w", err)
	}
	for _, entry := range entries {
		if !strings.HasPrefix(entry.Name(), ".stealth-managed-assets-") && !strings.HasPrefix(entry.Name(), ".stealth-managed-backup-") {
			continue
		}
		if err := os.RemoveAll(filepath.Join(layout.StateDir, entry.Name())); err != nil {
			return fmt.Errorf("remove stale managed asset transaction %q: %w", entry.Name(), err)
		}
	}
	return nil
}

func isManagedAssetPath(relativePath string) bool {
	switch filepath.ToSlash(filepath.Clean(relativePath)) {
	case "compose.production.yaml", "compose.setup.yaml", "console/deploy/nginx.conf", "telemetry/otel-collector.yaml", "telemetry/host-metrics.yaml", "telemetry/docker-logs.yaml", "telemetry/docker-stats.yaml":
		return filepath.Clean(relativePath) == filepath.FromSlash(relativePath)
	default:
		return false
	}
}

func removeManagedAssetTarget(path string) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("target is not a regular file")
	}
	return os.Remove(path)
}

func validateProductionComposeAsset(contents []byte) error {
	for _, marker := range []string{
		"  otel-collector:",
		"  telemetry-host:",
		"  telemetry-docker-logs:",
		"  telemetry-docker:",
		"  telemetry-docker-proxy:",
		"  telemetry_ingest:",
	} {
		if !bytes.Contains(contents, []byte(marker)) {
			return fmt.Errorf("missing current telemetry topology marker %q", marker)
		}
	}
	return nil
}

func validateMainCollectorAsset(contents []byte) error {
	for _, marker := range [][]byte{[]byte("exporters:"), []byte("clickhouse:")} {
		if !bytes.Contains(contents, marker) {
			return fmt.Errorf("missing main Collector marker %q", marker)
		}
	}
	if bytes.Contains(contents, []byte("file_log/docker:")) {
		return errors.New("main Collector still contains the Docker file-log receiver")
	}
	return nil
}

func (m *managedAssetMigration) commit() error {
	if m == nil {
		return errors.New("managed asset migration is nil")
	}
	if info, err := os.Lstat(m.previousBackup); err == nil {
		if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return errors.New("managed asset recovery path is not a directory")
		}
		if err := os.RemoveAll(m.previousBackup); err != nil {
			return fmt.Errorf("replace previous managed asset recovery set: %w", err)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect previous managed asset recovery set: %w", err)
	}
	backupDir, err := os.MkdirTemp(m.layout.StateDir, ".stealth-managed-backup-")
	if err != nil {
		return fmt.Errorf("create managed asset recovery set: %w", err)
	}
	m.backupDir = backupDir
	for index := range m.assets {
		asset := &m.assets[index]
		info, err := os.Lstat(asset.targetPath)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return m.failCommit(fmt.Errorf("inspect managed asset %q: %w", asset.spec.relativePath, err))
		}
		if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return m.failCommit(fmt.Errorf("managed asset %q is not a regular file", asset.spec.relativePath))
		}
		asset.existed = true
		asset.backupPath = filepath.Join(backupDir, filepath.FromSlash(asset.spec.relativePath))
		if err := os.MkdirAll(filepath.Dir(asset.backupPath), 0o700); err != nil {
			return m.failCommit(fmt.Errorf("prepare recovery path for %q: %w", asset.spec.relativePath, err))
		}
	}
	manifest := managedAssetRecoveryManifest{BackupDir: filepath.Base(backupDir), Assets: make([]managedAssetRecoveryEntry, 0, len(m.assets))}
	for _, asset := range m.assets {
		manifest.Assets = append(manifest.Assets, managedAssetRecoveryEntry{RelativePath: asset.spec.relativePath, Existed: asset.existed})
	}
	manifestContents, err := json.Marshal(manifest)
	if err != nil {
		return m.failCommit(fmt.Errorf("encode managed asset recovery journal: %w", err))
	}
	if err := WriteAtomic(filepath.Join(m.layout.StateDir, managedAssetPendingFile), manifestContents, 0o600); err != nil {
		return m.failCommit(fmt.Errorf("write managed asset recovery journal: %w", err))
	}
	for index := range m.assets {
		asset := &m.assets[index]
		if !asset.existed {
			continue
		}
		if err := os.Rename(asset.targetPath, asset.backupPath); err != nil {
			return m.failCommit(fmt.Errorf("save previous managed asset %q: %w", asset.spec.relativePath, err))
		}
		asset.backedUp = true
	}
	for index := range m.assets {
		asset := &m.assets[index]
		if err := os.MkdirAll(filepath.Dir(asset.targetPath), 0o700); err != nil {
			return m.failCommit(fmt.Errorf("create managed asset directory for %q: %w", asset.spec.relativePath, err))
		}
		if err := os.Rename(asset.stagePath, asset.targetPath); err != nil {
			return m.failCommit(fmt.Errorf("activate managed asset %q: %w", asset.spec.relativePath, err))
		}
		asset.installed = true
	}
	hasBackup := false
	for _, asset := range m.assets {
		if asset.existed {
			hasBackup = true
			break
		}
	}
	if hasBackup {
		if err := os.Rename(backupDir, m.previousBackup); err != nil {
			return m.failCommit(fmt.Errorf("publish managed asset recovery set: %w", err))
		}
		m.backupDir = m.previousBackup
		for index := range m.assets {
			if m.assets[index].existed {
				m.assets[index].backupPath = filepath.Join(m.previousBackup, filepath.FromSlash(m.assets[index].spec.relativePath))
			}
		}
	} else {
		_ = os.RemoveAll(backupDir)
		m.backupDir = ""
	}
	if err := os.Remove(filepath.Join(m.layout.StateDir, managedAssetPendingFile)); err != nil && !errors.Is(err, os.ErrNotExist) {
		return m.failCommit(fmt.Errorf("remove managed asset recovery journal: %w", err))
	}
	m.committed = true
	return nil
}

func (m *managedAssetMigration) failCommit(cause error) error {
	rollbackErr := m.rollback()
	return errors.Join(cause, rollbackErr)
}

func (m *managedAssetMigration) rollback() error {
	if m == nil {
		return nil
	}
	var rollbackErr error
	for index := len(m.assets) - 1; index >= 0; index-- {
		asset := &m.assets[index]
		if asset.installed {
			if err := os.Remove(asset.targetPath); err != nil && !errors.Is(err, os.ErrNotExist) {
				rollbackErr = errors.Join(rollbackErr, fmt.Errorf("remove activated asset %q: %w", asset.spec.relativePath, err))
			}
			asset.installed = false
		}
		if asset.backedUp && asset.backupPath != "" {
			if err := os.MkdirAll(filepath.Dir(asset.targetPath), 0o700); err != nil {
				rollbackErr = errors.Join(rollbackErr, err)
				continue
			}
			if err := os.Rename(asset.backupPath, asset.targetPath); err != nil {
				rollbackErr = errors.Join(rollbackErr, fmt.Errorf("restore managed asset %q: %w", asset.spec.relativePath, err))
			}
		}
	}
	if m.backupDir != "" {
		if err := os.RemoveAll(m.backupDir); err != nil {
			rollbackErr = errors.Join(rollbackErr, err)
		}
	}
	if m.stageDir != "" {
		if err := os.RemoveAll(m.stageDir); err != nil {
			rollbackErr = errors.Join(rollbackErr, err)
		}
	}
	if err := os.Remove(filepath.Join(m.layout.StateDir, managedAssetPendingFile)); err != nil && !errors.Is(err, os.ErrNotExist) {
		rollbackErr = errors.Join(rollbackErr, err)
	}
	m.committed = false
	return rollbackErr
}

func (m *managedAssetMigration) finalize() {
	if m == nil {
		return
	}
	if m.stageDir != "" {
		_ = os.RemoveAll(m.stageDir)
	}
	if m.backupDir != "" && m.backupDir != m.previousBackup {
		_ = os.RemoveAll(m.backupDir)
	}
}

// Wait checks the host-visible service endpoints for CLI plans and the
// Compose-network endpoints for browser handoff plans. A public URL is only
// probed when the plan explicitly requests the final ingress check.
func (e *Engine) Wait(ctx context.Context, plan Plan) error {
	values, err := ReadEnvFile(plan.Layout.EnvFile)
	if err != nil {
		return fmt.Errorf("read installation configuration: %w", err)
	}
	apiURL := strings.TrimRight(plan.InternalAPIURL, "/")
	consoleURL := strings.TrimRight(plan.InternalConsoleURL, "/")
	proxyURL := strings.TrimRight(plan.InternalProxyURL, "/")
	if apiURL == "" {
		apiURL = "http://127.0.0.1:" + PortOrDefault(values["API_HOST_PORT"], "18080")
	}
	if consoleURL == "" {
		consoleURL = "http://127.0.0.1:" + PortOrDefault(values["CONSOLE_HOST_PORT"], "13000")
	}
	if proxyURL == "" {
		proxyURL = "http://127.0.0.1:" + PortOrDefault(values["PROXY_HTTP_PORT"], "8080")
	}
	endpoints := []string{apiURL + "/healthz", apiURL + "/readyz", apiURL + "/version", consoleURL + "/", proxyURL + "/"}
	if plan.VerifyPublicURL && strings.TrimRight(plan.PublicURL, "/") != "" {
		endpoints = append(endpoints, strings.TrimRight(plan.PublicURL, "/")+"/")
	}
	maxWait := time.Duration(e.pollAttempts)*e.pollInterval + 30*time.Second
	waitContext, cancel := context.WithTimeout(ctx, maxWait)
	defer cancel()
	for attempt := 0; attempt < e.pollAttempts; attempt++ {
		if err := waitContext.Err(); err != nil {
			return err
		}
		allReady := true
		for _, endpoint := range endpoints {
			status, requestErr := e.httpStatus(waitContext, endpoint)
			if requestErr != nil || status < 200 || status >= 300 {
				allReady = false
				break
			}
		}
		if allReady {
			return nil
		}
		if attempt+1 < e.pollAttempts {
			if err := waitInterval(waitContext, e.pollInterval); err != nil {
				return err
			}
		}
	}
	return fmt.Errorf("services did not become ready after %d checks", e.pollAttempts)
}

func (e *Engine) runCompose(ctx context.Context, plan Plan, args ...string) error {
	composeArgs := []string{"compose"}
	if plan.Cloudflare {
		composeArgs = append(composeArgs, "--profile", "cloudflare")
	}
	composeFile := plan.Layout.ComposeFile
	if plan.Setup && plan.Layout.SetupComposeFile != "" {
		composeFile = plan.Layout.SetupComposeFile
	}
	if strings.TrimSpace(composeFile) == "" {
		return errors.New("Compose file is required")
	}
	composeArgs = append(composeArgs, "--env-file", plan.Layout.EnvFile, "-f", composeFile)
	composeArgs = append(composeArgs, args...)
	if err := e.runner.Run(ctx, plan.Layout.Root, e.output, e.output, "docker", composeArgs...); err != nil {
		return fmt.Errorf("docker compose %v failed: %w", args, err)
	}
	return nil
}

func (e *Engine) fetchAsset(ctx context.Context, assetURL string) ([]byte, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, assetURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create asset request: %w", err)
	}
	response, err := e.httpClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("download asset: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download asset returned HTTP %d", response.StatusCode)
	}
	contents, err := io.ReadAll(io.LimitReader(response.Body, maxAssetSize+1))
	if err != nil {
		return nil, fmt.Errorf("read downloaded asset: %w", err)
	}
	if len(contents) > maxAssetSize {
		return nil, errors.New("downloaded asset is unexpectedly large")
	}
	return contents, nil
}

// RunCommand exposes the same process boundary used by installation steps for
// narrowly scoped lifecycle operations such as removing the exact temporary
// onboarding container. Callers must validate any resource name before
// passing it here; this method is not a general shell interface.
func (e *Engine) RunCommand(ctx context.Context, dir, name string, args ...string) error {
	if e == nil || e.runner == nil {
		return errors.New("install engine is not configured")
	}
	return e.runner.Run(ctx, dir, io.Discard, io.Discard, name, args...)
}

func (e *Engine) httpStatus(ctx context.Context, endpoint string) (int, error) {
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return 0, err
	}
	response, err := e.httpClient.Do(request)
	if err != nil {
		return 0, err
	}
	defer response.Body.Close()
	_, _ = io.Copy(io.Discard, io.LimitReader(response.Body, 4096))
	return response.StatusCode, nil
}

func waitInterval(ctx context.Context, interval time.Duration) error {
	if interval <= 0 {
		return nil
	}
	timer := time.NewTimer(interval)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func acquireLock(stateDir string) (*os.File, error) {
	if strings.TrimSpace(stateDir) == "" {
		return nil, errors.New("installation state directory is required")
	}
	return AcquireProcessLock(stateDir, lockFileName, "installation")
}

// AcquireProcessLock takes a non-blocking exclusive advisory lock on
// stateDir/name and returns the open lock file. Closing the file releases the
// lock, so a crashed process cannot leave a stale lock behind. Callers use this
// to guarantee that only one process owns a long-running operation such as a
// host-side setup orchestration or a production install.
func AcquireProcessLock(stateDir, name, description string) (*os.File, error) {
	if strings.TrimSpace(stateDir) == "" {
		return nil, errors.New("lock directory is required")
	}
	name = strings.TrimSpace(name)
	if name == "" || name == "." || name == ".." || filepath.Base(name) != name || strings.ContainsAny(name, `/\`) {
		return nil, errors.New("lock name is invalid")
	}
	if err := os.MkdirAll(stateDir, 0o700); err != nil {
		return nil, fmt.Errorf("create %s lock directory: %w", description, err)
	}
	lockPath := filepath.Join(stateDir, name)
	file, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("open %s lock: %w", description, err)
	}
	if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
		_ = file.Close()
		if errors.Is(err, syscall.EWOULDBLOCK) {
			if description == "installation" {
				return nil, ErrOperationInProgress
			}
			return nil, fmt.Errorf("another %s operation is already running", description)
		}
		return nil, fmt.Errorf("lock %s: %w", description, err)
	}
	return file, nil
}

func safeError(err error) string {
	if err == nil {
		return ""
	}
	// Compose errors are allowed to include service names and status codes, but
	// never copy a command's output into a browser event. The command runner is
	// configured with a discard writer by the HTTP composition root.
	message := strings.TrimSpace(err.Error())
	if len(message) > 240 {
		message = message[:240]
	}
	return message
}

// The small wrappers below are intentionally exported so the CLI can delete
// its duplicate file/configuration implementation while preserving its
// existing tests and operator behavior.
func FileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Mode()&os.ModeSymlink == 0
}

func FileIsPrivate(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Mode().Perm()&0o077 == 0
}

func WritePrivateFile(path, contents string) error {
	return WriteAtomic(path, []byte(contents), 0o600)
}

func WriteAtomic(path string, contents []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".stealth-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func ReadEnvFile(path string) (map[string]string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	values := make(map[string]string)
	for lineNumber, rawLine := range strings.Split(string(contents), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return nil, fmt.Errorf("invalid config.env line %d", lineNumber+1)
		}
		values[key] = strings.Trim(value, " \t")
	}
	return values, nil
}

func ValidEnvKey(value string) bool {
	if value == "" {
		return false
	}
	for index, character := range value {
		if (character < 'A' || character > 'Z') && (character < 'a' || character > 'z') && (character < '0' || character > '9') && character != '_' {
			return false
		}
		if index == 0 && character >= '0' && character <= '9' {
			return false
		}
	}
	return true
}

func FormatEnvFile(values map[string]string) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("# Generated by Stealth. Keep this file private.\n")
	for _, key := range keys {
		builder.WriteString(key)
		builder.WriteByte('=')
		builder.WriteString(values[key])
		builder.WriteByte('\n')
	}
	return builder.String()
}

func MergeEnv(base map[string]string, updates map[string]string) (string, error) {
	values := make(map[string]string, len(base)+len(updates))
	for key, value := range base {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	for key, value := range updates {
		if !ValidEnvKey(key) || strings.ContainsAny(value, "\r\n\x00") {
			return "", fmt.Errorf("invalid configuration value for %s", key)
		}
		values[key] = value
	}
	return FormatEnvFile(values), nil
}

func PortOrDefault(raw, fallback string) string {
	value, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || value < 1 || value > 65535 {
		return fallback
	}
	return strconv.Itoa(value)
}
