package appruntime

import (
	"context"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/google/uuid"
)

const runtimeImageCachePressureRetryInterval = time.Minute

func (w *Worker) pruneCleanupHistoryIfDue(ctx context.Context) {
	now := time.Now()
	if !w.lastCleanupRetentionSweep.IsZero() && now.Sub(w.lastCleanupRetentionSweep) < defaultCleanupRetentionInterval {
		return
	}
	w.lastCleanupRetentionSweep = now
	if _, err := w.Store.PruneAppRuntimeCleanupJobs(ctx, cleanupHistoryBatchSize); err != nil && ctx.Err() == nil {
		w.Logger.Warn("App runtime cleanup history retention failed", "error", "runtime cleanup unavailable")
	}
}

func (w *Worker) sweepRuntimeImageCacheIfDue(ctx context.Context, currentDeploymentID uuid.UUID) {
	now := time.Now()
	if !w.nextImageCacheSweep.IsZero() && now.Before(w.nextImageCacheSweep) {
		return
	}
	if w.Metrics != nil {
		w.Metrics.AppRuntimeImageCacheLimitBytes.Set(float64(w.imageCacheMaxBytes()))
	}

	entries, err := w.Runtime.ListRuntimeImageCache(ctx)
	if err != nil {
		w.reportRuntimeImageCacheSweep("error", 0, 0, false, err)
		return
	}
	if err := validateRuntimeImageCacheEntries(entries); err != nil {
		w.reportRuntimeImageCacheSweep("error", 0, 0, false, err)
		return
	}
	cacheBytes, err := runtimeImageCacheSizeBytes(entries)
	if err != nil {
		w.reportRuntimeImageCacheSweep("error", 0, 0, false, err)
		return
	}
	if w.Metrics != nil {
		w.Metrics.AppRuntimeImageCacheAvailable.Set(1)
		w.Metrics.AppRuntimeImageCacheBytes.Set(float64(cacheBytes))
	}
	maxBytes := w.imageCacheMaxBytes()
	if cacheBytes <= maxBytes {
		w.reportRuntimeImageCacheSweep("completed", 0, cacheBytes, false, nil)
		return
	}

	candidateDeploymentIDs := make([]uuid.UUID, 0, len(entries))
	for _, entry := range entries {
		candidateDeploymentIDs = append(candidateDeploymentIDs, entry.DeploymentID)
	}
	protectedIDs, activeLease, err := w.Store.ListProtectedAppRuntimeDeploymentIDs(ctx, candidateDeploymentIDs)
	if err != nil {
		w.reportRuntimeImageCacheSweep("error", 0, cacheBytes, true, err)
		return
	}
	protected := make(map[uuid.UUID]struct{}, len(protectedIDs)+1)
	for _, deploymentID := range protectedIDs {
		if deploymentID == uuid.Nil || deploymentID.Version() != uuid.Version(7) {
			w.reportRuntimeImageCacheSweep("error", 0, cacheBytes, true, ErrImageVerification)
			return
		}
		protected[deploymentID] = struct{}{}
	}
	if currentDeploymentID != uuid.Nil {
		protected[currentDeploymentID] = struct{}{}
	}
	if activeLease {
		w.Logger.Warn("Stealth App runtime image cache exceeds its limit while runtime work is protected", "cache_bytes", cacheBytes, "limit_bytes", maxBytes)
		w.reportRuntimeImageCacheSweep("pressure", 0, cacheBytes, true, nil)
		return
	}
	containerReferences, err := w.Runtime.ListManagedAppImageReferences(ctx)
	if err != nil {
		w.reportRuntimeImageCacheSweep("error", 0, cacheBytes, true, err)
		return
	}
	for _, reference := range containerReferences {
		if reference.DeploymentID == uuid.Nil || reference.DeploymentID.Version() != uuid.Version(7) || !validImageID(reference.ImageID) {
			w.reportRuntimeImageCacheSweep("error", 0, cacheBytes, true, ErrRuntimeOwnershipConflict)
			return
		}
		protected[reference.DeploymentID] = struct{}{}
	}

	ordered := slices.Clone(entries)
	slices.SortFunc(ordered, func(left, right RuntimeImageCacheEntry) int {
		// UUIDv7 is generated by Stealth at deployment creation. It is a
		// trusted stable age signal; OCI Created metadata is caller-controlled.
		if comparison := strings.Compare(left.DeploymentID.String(), right.DeploymentID.String()); comparison != 0 {
			return comparison
		}
		return strings.Compare(left.Reference, right.Reference)
	})

	attempted := 0
	removed := 0
	var reclaimedBytes int64
	removalFailed := false
	for _, entry := range ordered {
		if cacheBytes <= w.imageCacheTargetBytes() || attempted >= maxRuntimeImageGCRemovalsPerSweep {
			break
		}
		if _, isProtected := protected[entry.DeploymentID]; isProtected {
			continue
		}
		// Re-read the protected set before each destructive Docker operation.
		// A deployment may have become desired after the initial inventory.
		latestIDs, leaseActive, err := w.Store.ListProtectedAppRuntimeDeploymentIDs(ctx, []uuid.UUID{entry.DeploymentID})
		if err != nil {
			w.reportRuntimeImageCacheSweepWithProgress("error", reclaimedBytes, cacheBytes, true, err, removed > 0)
			return
		}
		if leaseActive {
			w.Logger.Warn("Stealth App runtime image cache exceeds its limit while runtime work is protected", "cache_bytes", cacheBytes, "limit_bytes", maxBytes)
			w.reportRuntimeImageCacheSweepWithProgress("pressure", reclaimedBytes, cacheBytes, true, nil, removed > 0)
			return
		}
		latestProtected := false
		for _, latestID := range latestIDs {
			if latestID == entry.DeploymentID {
				latestProtected = true
				break
			}
		}
		if latestProtected || entry.DeploymentID == currentDeploymentID {
			continue
		}
		beforeBytes := cacheBytes
		attempted++
		if err := w.Runtime.RemoveRuntimeImageTag(ctx, entry); err != nil {
			removalFailed = true
			w.Logger.Warn("Stealth App runtime image cache entry could not be removed", "deployment_id", entry.DeploymentID, "reason", safeRuntimeError(err))
			continue
		}
		removed++
		remaining := make([]RuntimeImageCacheEntry, 0, len(entries))
		for _, candidate := range entries {
			if candidate.Reference != entry.Reference {
				remaining = append(remaining, candidate)
			}
		}
		entries = remaining
		cacheBytes, err = runtimeImageCacheSizeBytes(entries)
		if err != nil {
			w.reportRuntimeImageCacheSweepWithProgress("error", reclaimedBytes, beforeBytes, true, err, removed > 0)
			return
		}
		if cacheBytes < beforeBytes {
			reclaimedBytes += beforeBytes - cacheBytes
		}
		if w.Metrics != nil {
			w.Metrics.AppRuntimeImageCacheBytes.Set(float64(cacheBytes))
		}
	}

	pressure := cacheBytes > maxBytes
	result := "completed"
	if removalFailed {
		result = "error"
	}
	if pressure {
		if result == "completed" {
			result = "pressure"
		}
		w.Logger.Warn("Stealth App runtime image cache remains above its configured limit", "cache_bytes", cacheBytes, "limit_bytes", maxBytes)
	}
	w.reportRuntimeImageCacheSweepWithProgress(result, reclaimedBytes, cacheBytes, pressure, nil, removed > 0)
}

func (w *Worker) imageCacheMaxBytes() int64 {
	if w.ImageCacheMaxBytes < 1<<20 || w.ImageCacheMaxBytes > 1<<40 {
		return defaultRuntimeImageCacheMaxBytes
	}
	return w.ImageCacheMaxBytes
}

func (w *Worker) imageCacheTargetBytes() int64 {
	maxBytes := w.imageCacheMaxBytes()
	if w.ImageCacheTargetBytes < 1<<20 || w.ImageCacheTargetBytes >= maxBytes {
		return defaultRuntimeImageCacheTargetBytes
	}
	return w.ImageCacheTargetBytes
}

func validateRuntimeImageCacheEntries(entries []RuntimeImageCacheEntry) error {
	seen := make(map[string]struct{}, len(entries))
	for _, entry := range entries {
		deploymentID, ok := ParseRuntimeImageReference(entry.Reference)
		if !ok || deploymentID != entry.DeploymentID || deploymentID.Version() != uuid.Version(7) || !validImageID(entry.ImageID) || entry.SizeBytes < 0 {
			return ErrImageVerification
		}
		if _, duplicate := seen[entry.Reference]; duplicate {
			return ErrImageVerification
		}
		seen[entry.Reference] = struct{}{}
	}
	return nil
}

func runtimeImageCacheSizeBytes(entries []RuntimeImageCacheEntry) (int64, error) {
	sizes := make(map[string]int64, len(entries))
	for _, entry := range entries {
		if !validImageID(entry.ImageID) || entry.SizeBytes < 0 {
			return 0, ErrImageVerification
		}
		if existing, ok := sizes[entry.ImageID]; ok {
			if existing != entry.SizeBytes {
				return 0, ErrImageVerification
			}
			continue
		}
		sizes[entry.ImageID] = entry.SizeBytes
	}
	var total int64
	for _, size := range sizes {
		if size > int64(^uint64(0)>>1)-total {
			return 0, fmt.Errorf("runtime image cache size overflow")
		}
		total += size
	}
	return total, nil
}

func boundedMaintenanceBackoff(base time.Duration, attempt int, maximum time.Duration) time.Duration {
	if base <= 0 {
		base = time.Second
	}
	if maximum < base {
		maximum = base
	}
	if attempt < 1 {
		attempt = 1
	}
	delay := base
	for index := 1; index < attempt && delay < maximum; index++ {
		if delay > maximum/2 {
			return maximum
		}
		delay *= 2
	}
	if delay > maximum {
		return maximum
	}
	return delay
}

func (w *Worker) imageCacheSweepInterval() time.Duration {
	if w.ImageCacheGCSweepInterval < time.Minute || w.ImageCacheGCSweepInterval > 24*time.Hour {
		return defaultRuntimeImageGCSweepInterval
	}
	return w.ImageCacheGCSweepInterval
}

func (w *Worker) reportRuntimeImageCacheSweep(result string, reclaimedBytes, cacheBytes int64, pressure bool, err error) {
	w.reportRuntimeImageCacheSweepWithProgress(result, reclaimedBytes, cacheBytes, pressure, err, false)
}

func (w *Worker) reportRuntimeImageCacheSweepWithProgress(result string, reclaimedBytes, cacheBytes int64, pressure bool, err error, madeProgress bool) {
	if result != "completed" && result != "error" && result != "pressure" {
		result = "error"
	}
	interval := w.imageCacheSweepInterval()
	now := time.Now()
	if result == "error" {
		if w.imageCacheFailureCount < 32 {
			w.imageCacheFailureCount++
		}
		delay := boundedMaintenanceBackoff(interval, w.imageCacheFailureCount, maxRuntimeImageGCBackoff)
		if pressure && madeProgress {
			delay = runtimeImageCachePressureRetryInterval
		}
		w.nextImageCacheSweep = now.Add(delay)
	} else {
		w.imageCacheFailureCount = 0
		delay := interval
		if pressure && madeProgress {
			delay = runtimeImageCachePressureRetryInterval
		}
		w.nextImageCacheSweep = now.Add(delay)
	}
	if w.Metrics != nil {
		w.Metrics.AppRuntimeImageGCTotal.WithLabelValues(result).Inc()
		w.Metrics.AppRuntimeImageGCReclaimedBytes.Add(float64(reclaimedBytes))
		w.Metrics.AppRuntimeImageCachePressure.Set(0)
		if pressure {
			w.Metrics.AppRuntimeImageCachePressure.Set(1)
		}
		if err != nil {
			w.Metrics.AppRuntimeImageCacheAvailable.Set(0)
		} else {
			w.Metrics.AppRuntimeImageCacheAvailable.Set(1)
			w.Metrics.AppRuntimeImageCacheBytes.Set(float64(cacheBytes))
		}
	}
	if err != nil {
		w.Logger.Warn("Stealth App runtime image cache maintenance failed", "reason", safeRuntimeError(err))
	}
}
