"use client";

import Link from "next/link";
import { type ColumnDef } from "@tanstack/react-table";
import { Database as DatabaseIcon, FunctionSquare, Globe2, HardDrive, MoreHorizontal } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useCreateAPIKey, useCreateBucket, useCreateDatabase, useCreateFunction, useCreateProjectUser, useCreateSite, useCreateWebhook } from "@/api/mutations";
import { nextCursor } from "@/api/pagination";
import { useDatabases, useFunctions, useProjectAPIKeys, useProjectUsers, useSites, useStorageBuckets, useWebhooks } from "@/api/queries";
import type { APIKey, Database, ProjectUser, Site, StorageBucket, StealthFunction, Webhook } from "@/api/types";
import type { components } from "@/api/generated/schema";
import { CreateDialog } from "@/components/create-dialog";
import { DataTable, type ServerPagination } from "@/components/data-table";
import { EmptyState } from "@/components/empty-state";
import { ErrorState } from "@/components/feedback/error-state";
import { PageHeader } from "@/components/page-header";
import { ResourceTableCard } from "@/components/resource-page";
import { OneTimeSecretDialog } from "@/components/one-time-secret-dialog";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { formatBytes, formatDate } from "@/lib/format";
import { useCursorPagination } from "@/hooks/use-cursor-pagination";
import { FUNCTION_RUNTIME_OPTIONS, isFunctionRuntime, SITE_FRAMEWORK_OPTIONS } from "@/lib/capabilities/runtime-catalog";

function pageControls(navigation: ReturnType<typeof useCursorPagination>, next: string | null, isFetching: boolean): ServerPagination {
  return { canFirst: navigation.canFirst, canPrevious: navigation.canPrevious, canNext: Boolean(next), onFirst: navigation.goFirst, onPrevious: navigation.goPrevious, onNext: () => navigation.goNext(next), isFetching };
}

function ProjectResourceIntro({ icon: Icon, title, description }: { icon: typeof FunctionSquare; title: string; description: string }) {
  return <div className="mb-5 flex items-center gap-3 rounded-lg border border-stealth-border bg-white/[0.015] px-3.5 py-3"><div className="flex size-8 shrink-0 items-center justify-center rounded-lg border border-cyan-300/20 bg-cyan-300/10 text-cyan-200"><Icon className="size-4" /></div><p className="text-xs leading-5 text-slate-500"><span className="font-medium text-slate-300">{title}.</span> {description}</p></div>;
}

function openCreateDialog() {
  document.querySelector<HTMLButtonElement>("[data-create-dialog]")?.click();
}

export function FunctionsView({ organizationId, projectId }: { organizationId: string; projectId: string }) {
  const navigation = useCursorPagination();
  const query = useFunctions(projectId, { cursor: navigation.cursor });
  const create = useCreateFunction(projectId);
  const base = `/organizations/${organizationId}/projects/${projectId}`;
  const columns: ColumnDef<StealthFunction, unknown>[] = [{ accessorKey: "name", header: "Function", cell: ({ row }) => <Link href={`${base}/functions/${row.original.id}`} className="font-medium text-white hover:text-cyan-200"><span className="block">{row.original.name}</span><span className="mt-0.5 block text-[11px] text-slate-600">{row.original.entrypoint}</span></Link> }, { accessorKey: "runtime", header: "Runtime", cell: ({ row }) => <span className="font-mono text-xs text-slate-400">{row.original.runtime}</span> }, { accessorKey: "status", header: "Status", cell: ({ row }) => <StatusBadge status={row.original.status} /> }, { accessorKey: "active_deployment_id", header: "Deployment", cell: ({ row }) => row.original.active_deployment_id ? <Badge variant="success">active</Badge> : <span className="text-xs text-slate-600">Not deployed</span> }, { accessorKey: "updated_at", header: "Updated", cell: ({ row }) => formatDate(row.original.updated_at) }];
  return <><PageHeader eyebrow="Compute" title="Functions" description="Run backend code on Stealth-managed infrastructure." actions={<CreateDialog title="Create a function" description="The function definition is stored by the Go API. Source deployment happens separately through an archive." fields={[{ name: "name", label: "Name", placeholder: "api-handler" }, { name: "runtime", label: "Runtime", type: "select", defaultValue: FUNCTION_RUNTIME_OPTIONS[0].value, options: FUNCTION_RUNTIME_OPTIONS, help: "Available runtimes are centralized from the current OpenAPI enum." }, { name: "entrypoint", label: "Entrypoint", placeholder: "src/index.main" }, { name: "description", label: "Description", type: "textarea", required: false }]} pending={create.isPending} onSubmit={async (values) => { if (!isFunctionRuntime(values.runtime)) { toast.error("Runtime is not supported by the current Stealth API."); return; } await create.mutateAsync({ name: values.name, runtime: values.runtime as components["schemas"]["FunctionRuntime"], entrypoint: values.entrypoint, commands: "", timeout_seconds: 15, enabled: true, logging: true, description: values.description }); toast.success("Function created"); }} />} /><ProjectResourceIntro icon={FunctionSquare} title="Functions" description="Deploy immutable source archives, then inspect builds and executions without mixing backend business logic into the console." />{query.isError ? <ErrorState error={query.error} retry={() => query.refetch()} /> : query.data?.functions.length ? <ResourceTableCard data={query.data.functions} searchable={(item, term) => `${item.name} ${item.runtime} ${item.status}`.toLowerCase().includes(term)} serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)}>{(filtered, pagination) => <DataTable data={filtered} columns={columns} serverPagination={pagination} />}</ResourceTableCard> : query.isLoading ? <Card><DataTable data={[]} columns={columns} loading /></Card> : <EmptyState title="No functions yet" description="Functions give your project a small, deployable compute surface with logs and execution history." actionLabel="Create function" action={openCreateDialog} />}</>;
}

export function SitesView({ organizationId, projectId }: { organizationId: string; projectId: string }) {
  const navigation = useCursorPagination();
  const query = useSites(projectId, { cursor: navigation.cursor });
  const create = useCreateSite(projectId);
  const base = `/organizations/${organizationId}/projects/${projectId}`;
  const columns: ColumnDef<Site, unknown>[] = [{ accessorKey: "name", header: "Site", cell: ({ row }) => <Link href={`${base}/sites/${row.original.id}`} className="font-medium text-white hover:text-violet-200"><span className="block">{row.original.name}</span><span className="mt-0.5 block text-[11px] text-slate-600">{row.original.framework}</span></Link> }, { accessorKey: "status", header: "Status", cell: ({ row }) => <StatusBadge status={row.original.status} /> }, { accessorKey: "active_deployment_id", header: "Deployment", cell: ({ row }) => row.original.active_deployment_id ? <Badge variant="success">active</Badge> : <span className="text-xs text-slate-600">Not deployed</span> }, { accessorKey: "artifact_used_bytes", header: "Artifact", cell: ({ row }) => `${formatBytes(row.original.artifact_used_bytes)} / ${formatBytes(row.original.artifact_quota_bytes)}` }, { accessorKey: "updated_at", header: "Updated", cell: ({ row }) => formatDate(row.original.updated_at) }];
  return <><PageHeader eyebrow="Compute" title="Sites" description="Deploy static sites from an archive or a public GitHub/GitLab source." actions={<CreateDialog title="Create a site" description="Create the site boundary first, then add a deployment." fields={[{ name: "name", label: "Name", placeholder: "marketing-site" }]} pending={create.isPending} onSubmit={async (values) => { await create.mutateAsync({ name: values.name, framework: SITE_FRAMEWORK_OPTIONS[0].value, enabled: true }); toast.success("Site created"); }} />} /><ProjectResourceIntro icon={Globe2} title="Sites" description="Site deployments are immutable and asynchronous. Deployment state is read from the actual site endpoints." />{query.isError ? <ErrorState error={query.error} retry={() => query.refetch()} /> : query.data?.sites.length ? <ResourceTableCard data={query.data.sites} searchable={(item, term) => `${item.name} ${item.status}`.toLowerCase().includes(term)} serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)}>{(filtered, pagination) => <DataTable data={filtered} columns={columns} serverPagination={pagination} />}</ResourceTableCard> : query.isLoading ? <Card><DataTable data={[]} columns={columns} loading /></Card> : <EmptyState title="No sites yet" description="Create a site when you are ready to publish a static application or documentation surface." actionLabel="Create site" action={openCreateDialog} />}</>;
}

export function DatabasesView({ organizationId, projectId }: { organizationId: string; projectId: string }) {
  const navigation = useCursorPagination();
  const query = useDatabases(projectId, { cursor: navigation.cursor });
  const create = useCreateDatabase(projectId);
  const base = `/organizations/${organizationId}/projects/${projectId}`;
  const columns: ColumnDef<Database, unknown>[] = [{ accessorKey: "name", header: "Database", cell: ({ row }) => <Link href={`${base}/databases/${row.original.id}`} className="font-medium text-white hover:text-amber-200">{row.original.name}</Link> }, { accessorKey: "id", header: "Database ID", cell: ({ row }) => <span className="font-mono text-xs text-slate-500">{row.original.id.slice(0, 8)}…</span> }, { accessorKey: "updated_at", header: "Updated", cell: ({ row }) => formatDate(row.original.updated_at) }, { id: "open", header: "", cell: ({ row }) => <Button asChild size="sm" variant="ghost"><Link href={`${base}/databases/${row.original.id}`}>Browse <MoreHorizontal className="size-3.5" /></Link></Button> }];
  return <><PageHeader eyebrow="Data" title="Databases" description="Browse typed tables, indexes, relationships, backups, and rows without exposing a fake SQL editor." actions={<CreateDialog title="Create a database" description="A database gives your project a typed schema boundary." fields={[{ name: "name", label: "Name", placeholder: "primary" }]} pending={create.isPending} onSubmit={async (values) => { await create.mutateAsync({ name: values.name }); toast.success("Database created"); }} />} /><ProjectResourceIntro icon={DatabaseIcon} title="Typed data layer" description="The API exposes schema and row operations. Query execution is intentionally not presented because the backend does not provide it." />{query.isError ? <ErrorState error={query.error} retry={() => query.refetch()} /> : query.data?.databases.length ? <Card><DataTable data={query.data.databases} columns={columns} serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)} /></Card> : query.isLoading ? <Card><DataTable data={[]} columns={columns} loading /></Card> : <EmptyState title="No databases yet" description="Create a database to define tables and browse rows through the platform API." actionLabel="Create database" action={openCreateDialog} />}</>;
}

export function StorageView({ organizationId, projectId }: { organizationId: string; projectId: string }) {
  const navigation = useCursorPagination();
  const query = useStorageBuckets(projectId, { cursor: navigation.cursor });
  const create = useCreateBucket(projectId);
  const base = `/organizations/${organizationId}/projects/${projectId}`;
  const columns: ColumnDef<StorageBucket, unknown>[] = [{ accessorKey: "name", header: "Bucket", cell: ({ row }) => <Link href={`${base}/storage/${row.original.id}`} className="font-medium text-white hover:text-emerald-200">{row.original.name}</Link> }, { accessorKey: "used_bytes", header: "Used", cell: ({ row }) => `${formatBytes(row.original.used_bytes)} / ${formatBytes(row.original.quota_bytes)}` }, { accessorKey: "file_security", header: "File security", cell: ({ row }) => <Badge variant={row.original.file_security ? "success" : "warning"}>{row.original.file_security ? "Enabled" : "Disabled"}</Badge> }, { accessorKey: "updated_at", header: "Updated", cell: ({ row }) => formatDate(row.original.updated_at) }];
  return <><PageHeader eyebrow="Data" title="Storage" description="Flat object storage for files and artifacts, with backend-defined permissions." actions={<CreateDialog title="Create a bucket" description="Bucket names are lowercase and hyphenated. Folders are not modeled by this API." fields={[{ name: "name", label: "Name", placeholder: "assets" }]} pending={create.isPending} onSubmit={async (values) => { await create.mutateAsync({ name: values.name, file_security: true }); toast.success("Bucket created"); }} />} /><ProjectResourceIntro icon={HardDrive} title="Buckets" description="Files are stored as safe object names. The console keeps the explorer flat because the backend does not expose folder semantics." />{query.isError ? <ErrorState error={query.error} retry={() => query.refetch()} /> : query.data?.buckets.length ? <Card><DataTable data={query.data.buckets} columns={columns} serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)} /></Card> : query.isLoading ? <Card><DataTable data={[]} columns={columns} loading /></Card> : <EmptyState title="No buckets yet" description="Create a bucket for user uploads, public assets, or build artifacts." actionLabel="Create bucket" action={openCreateDialog} />}</>;
}

export function UsersView({ projectId }: { projectId: string }) {
  const navigation = useCursorPagination();
  const query = useProjectUsers(projectId, { cursor: navigation.cursor });
  const create = useCreateProjectUser(projectId);
  const columns: ColumnDef<ProjectUser, unknown>[] = [{ accessorKey: "email", header: "Identity", cell: ({ row }) => <div><p className="font-medium text-white">{row.original.email}</p><p className="text-xs text-slate-500">{row.original.name ?? "Unnamed user"}</p></div> }, { accessorKey: "status", header: "Status", cell: ({ row }) => <StatusBadge status={row.original.status} /> }, { accessorKey: "email_verified", header: "Verified", cell: ({ row }) => row.original.email_verified ? <Badge variant="success">Verified</Badge> : <Badge variant="warning">Pending</Badge> }, { accessorKey: "created_at", header: "Created", cell: ({ row }) => formatDate(row.original.created_at) }];
  return <><PageHeader eyebrow="Auth" title="Users" description="Application users for this project. Console account sessions and project users are separate domains." actions={<CreateDialog title="Create an application user" description="The password is accepted by the API and is not stored in the console." fields={[{ name: "email", label: "Email", type: "email" }, { name: "password", label: "Temporary password", type: "password", help: "Minimum 12 characters." }, { name: "name", label: "Name", required: false }]} pending={create.isPending} onSubmit={async (values) => { await create.mutateAsync({ email: values.email, password: values.password, name: values.name || null }); toast.success("User created"); }} />} />{query.isError ? <ErrorState error={query.error} retry={() => query.refetch()} /> : query.data?.users.length ? <Card><DataTable data={query.data.users} columns={columns} serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)} /></Card> : query.isLoading ? <Card><DataTable data={[]} columns={columns} loading /></Card> : <EmptyState title="No application users yet" description="Create an application identity to test authentication and user-scoped data." actionLabel="Create user" action={openCreateDialog} />}</>;
}

export function WebhooksView({ organizationId, projectId }: { organizationId: string; projectId: string }) {
  const navigation = useCursorPagination();
  const query = useWebhooks(projectId, { cursor: navigation.cursor });
  const create = useCreateWebhook(projectId);
  const base = `/organizations/${organizationId}/projects/${projectId}`;
  const columns: ColumnDef<Webhook, unknown>[] = [{ accessorKey: "name", header: "Webhook", cell: ({ row }) => <Link href={`${base}/webhooks/${row.original.id}`} className="font-medium text-white hover:text-pink-200">{row.original.name}</Link> }, { accessorKey: "url", header: "Endpoint", cell: ({ row }) => <span className="max-w-xs truncate font-mono text-xs text-slate-500">{row.original.url}</span> }, { accessorKey: "enabled", header: "State", cell: ({ row }) => <StatusBadge status={row.original.enabled ? "active" : "inactive"} /> }, { accessorKey: "failure_count", header: "Failures", cell: ({ row }) => row.original.failure_count }, { accessorKey: "last_delivery_at", header: "Last delivery", cell: ({ row }) => formatDate(row.original.last_delivery_at) }];
  const [secret, setSecret] = useState<string | null>(null);
  return <><PageHeader eyebrow="Integrations" title="Webhooks" description="Deliver platform events to HTTPS endpoints and inspect delivery metadata." actions={<CreateDialog title="Create a webhook" description="Copy the signing secret before closing this dialog. Stealth will not show it again." fields={[{ name: "name", label: "Name", placeholder: "production-events" }, { name: "url", label: "HTTPS URL", type: "url", placeholder: "https://example.com/hooks" }, { name: "events", label: "Events", required: false, defaultValue: "*", help: "Comma-separated event names, or * for all." }]} pending={create.isPending} onSubmit={async (values) => { const result = await create.mutateAsync({ name: values.name, url: values.url, events: values.events.split(",").map((event) => event.trim()).filter(Boolean), enabled: true }); const secretResult = result as components["schemas"]["WebhookSecretResponse"] | undefined; if (secretResult?.secret) setSecret(secretResult.secret); create.reset(); toast.success("Webhook created"); }} />} />{query.isError ? <ErrorState error={query.error} retry={() => query.refetch()} /> : <Card><DataTable data={query.data?.webhooks ?? []} columns={columns} loading={query.isLoading} empty="No webhooks yet." serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)} /></Card>}<OneTimeSecretDialog key={secret ?? "empty-webhook-secret"} secret={secret} title="Copy this signing secret now" description="This secret is returned once by the Go API. Save it before finishing; Stealth will not show it again." onDone={() => setSecret(null)} /></>;
}

const defaultScopes = "users.read,databases.read,storage.read,functions.read,sites.read,webhooks.read";

export function APIKeysView({ projectId }: { projectId: string }) {
  const navigation = useCursorPagination();
  const query = useProjectAPIKeys(projectId, { cursor: navigation.cursor });
  const create = useCreateAPIKey(projectId);
  const [secret, setSecret] = useState<string | null>(null);
  const columns: ColumnDef<APIKey, unknown>[] = [{ accessorKey: "name", header: "Key", cell: ({ row }) => <div><p className="font-medium text-white">{row.original.name}</p><p className="font-mono text-xs text-slate-600">{row.original.prefix}••••</p></div> }, { accessorKey: "scopes", header: "Scopes", cell: ({ row }) => <span className="text-xs text-slate-400">{row.original.scopes.length} scopes</span> }, { accessorKey: "last_used_at", header: "Last used", cell: ({ row }) => formatDate(row.original.last_used_at) }, { accessorKey: "revoked_at", header: "State", cell: ({ row }) => row.original.revoked_at ? <StatusBadge status="revoked" /> : <StatusBadge status="active" /> }];
  if (query.error) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  return <><PageHeader eyebrow="Integrations" title="API keys" description="Project-bound keys are managed by the Go API. Secrets are shown once and never persisted by this UI." actions={<CreateDialog title="Create an API key" description="Copy the secret before closing this dialog. Stealth will not show it again." fields={[{ name: "name", label: "Name", placeholder: "CI deploy key" }, { name: "scopes", label: "Scopes", defaultValue: defaultScopes, help: "Comma-separated scopes such as functions.write or sites.write." }]} pending={create.isPending} onSubmit={async (values) => { const scopes = values.scopes.split(",").map((scope) => scope.trim()).filter(Boolean) as components["schemas"]["CreateProjectAPIKeyRequest"]["scopes"]; const result = await create.mutateAsync({ name: values.name, scopes }); const keyResult = result as components["schemas"]["CreateProjectAPIKeyResponse"] | undefined; if (keyResult?.secret) setSecret(keyResult.secret); create.reset(); toast.success("API key created"); }} />} /><Card><DataTable data={query.data?.keys ?? []} columns={columns} loading={query.isLoading} empty="No API keys yet." serverPagination={pageControls(navigation, nextCursor(query.data), query.isFetching)} /></Card><OneTimeSecretDialog key={secret ?? "empty-api-key-secret"} secret={secret} title="Copy this key now" description="This secret is returned once by the Go API. Save it before finishing; Stealth will not show it again." onDone={() => setSecret(null)} /></>;
}
